### ISSUE TITLE
ML.NET Model Builder - Feature Requests

### ISSUE THREAD

**Issue by nsulikowski** [dotnet/machinelearning-modelbuilder#1056]
Feedback:
1) VS Extension: Save the content of the output window (with the logs about the training) as a text file when adding the projects *ML.Model, *ML.ConsoleApp
2) VS Extension: Allow to change the name of the added projects *ML.Model, *ML.ConsoleApp (may be to prefix them so that they are unique across different sessions?
3) VS Extension: Rename "Text Classification" scenario to something without the "Text", since that scenario is not limited to text
4) VS Extension: Print the equivalent command arguments to the ml.net model builder cli
5) Model Builder API: Can you add the possibility of generating the code too? (same as the VS Extension)

**Comment by beccamc** [comment]
@briacht For visibility

**Comment by JakeRadMSFT** [comment]
Thanks for the recommendations! We're doing a fairly major re-work and we'll take these recommendations into consideration along the way. Greatly appreciated!

**Comment by JakeRadMSFT** [comment]
@nsulikowski Would you be interested in trying out a pre-release build?

We've changed how projects are generated and added a mbconfig file that can also be used in the CLI.

Here is the link to sign up: aka.ms/mb-private-preview

You can see some of the updates in our community standup - 
https://www.youtube.com/watch?v=jWr_D_R2nZw&list=PLdo4fOcmZ0oX-DBuRG4u58ZTAJgBAeQ-t&index=4

**Comment by nsulikowski** [comment]
Yes I will. Thanks.

**Comment by beccamc** [comment]
@JakeRadMSFT To break this item up.

**Comment by JakeRadMSFT** [comment]
- [ ] 1) VS Extension: Save the content of the output window (with the logs about the training) as a text file when adding the projects ML.Model, ML.ConsoleApp
- [ ] 2) VS Extension: Allow to change the name of the added projects ML.Model, ML.ConsoleApp (may be to prefix them so that they are unique across different sessions?
- [ ] 3) VS Extension: Rename "Text Classification" scenario to something without the "Text", since that scenario is not limited to text
- [ ] 4) VS Extension: Print the equivalent command arguments to the ml.net model builder cli
- [ ] 5) Model Builder API: Can you add the possibility of generating the code too? (same as the VS Extension)

**Comment by JakeRadMSFT** [comment]
@nsulikowski what do you use from the output window? If we move it somewhere in model builder or in the MB Config ... would that resolve 1?

I believe 2 is resolved but I'll test it out to verify.



The upcoming CLI you'll be able to retrain by passing the mbconfig. Does that resolve  number 4?

Can you add more details for number 5? What do you mean by Model Builder API? Do you mean the ML.NET AutoML API?

**Comment by nsulikowski** [comment]
Hi @JakeRadMSFT, 
Great. Thanks for making all the amazing improvements.
By 5) I meant generating the c# to train and run a model (as you do in the addin), but be able to do it when I run automl using the api. Does that make sense?

**Comment by beccamc** [comment]
Tracking item # 1 in the Re-opening train tab issue above. Item # 5 should be resolved by the AutoML changes. 

- [ ] 1) VS Extension: Save the content of the output window (with the logs about the training) as a text file when adding the projects ML.Model, ML.ConsoleApp
- [x] 2) VS Extension: Allow to change the name of the added projects ML.Model, ML.ConsoleApp (may be to prefix them so that they are unique across different sessions? **Resolved: You can now specify project name on project generation**
- [x] 3) VS Extension: Rename "Text Classification" scenario to something without the "Text", since that scenario is not limited to text **Resolved: Data Classification**
- [ ] 4) VS Extension: Print the equivalent command arguments to the ml.net model builder cli
- [ ] 5) Model Builder API: Can you add the possibility of generating the code too? (same as the VS Extension)

**Comment by luisquintanilla** [comment]
Thanks for this issue @nsulikowski 

Closing this issue since it's already being tracked in #1582 and 4 is already possible by using the `mlnet train --training-config <MBCONFIG-PATH>` command in the [latest release of the ML.NET CLI](https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-ml-net-cli).

If you have additional feedback, please feel free to create a new issue.
