### ISSUE TITLE
Predict button not highlighted/active

### ISSUE THREAD

**Issue by whitmark** [dotnet/machinelearning-modelbuilder#1067]
**System Information (please complete the following information):**
 - Model Builder Version:  16.1.0.2047901
 - Visual Studio Version: 16.7.7

**Describe the bug**
- Using the Classification scenario, ran a binary classification experiment (Label: 0 or 1) using 19.5K rows and 98 columns that seemed to train fine for 600 seconds.
- However, in the Evaluation section, the Predict button did not activate so I could not test the prediction capabilities.
- I did not notice any runtime errors/issues.
- What might be preventing this feature from activating?

![Predict Button not Active](https://user-images.githubusercontent.com/8396992/97587775-26d12780-19d2-11eb-9311-790ee983b2b5.jpg)

**Comment by beccamc** [comment]
@whitmark Thanks for reporting this problem. Likely, the predict button isn't enabled because you have some column(s) with empty values. For 98 columns, that's pretty annoying blocking behavior. I'm looking into why we disable that, and if we can remove that behavior so you can predict with some values empty. 

To unblock yourself you can look through all the columns and add a value to the missing one. Again, I know this is annoying so we'll look into changing it.

**Comment by whitmark** [comment]
@beccamc Thanks to your note I reviewed my csv training data and noticed that each item in the last column had a comma after it thereby generating an extra column of missing values upon import.  Once I removed the extra comma, everything ran as expected.  Thanks!
