### ISSUE TITLE
Delimiter Change before  column to predict section  mess list of column names 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1079]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. select TextClassification scenario
2. choose tour text dataset
3. Click on advanced data options.. link on the data page
4. change the  column separator --> click save button 
5. select column to predict 

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**

![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/095b4392-423a-41d0-88a0-1624a674d643)
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/e9576c19-f124-4e2c-accc-506853219f4d)
**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
@zewditu This is a tab separated file right? And you changed it to a comma/semi-colon? If yes, this looks expected to me. You've changed the separator to a comma/semi-colon. There are no comma/semi-colons. When it tries to parse the file it thinks it is one column because there are no separators found. When printing, it puts the tabs into the printed lines. This makes it look really weird, but it's doing what you told it to do.

**Comment by zewditu** [comment]
@beccamc  yes, it is expected, thanks for your explanations.
