### ISSUE TITLE
export onnx

### ISSUE THREAD

**Issue by r9guy** [dotnet/machinelearning-modelbuilder#1182]
it's very hard for a non-data scientist to generate onnx models. 
it would be really great if you could give an option in the GUI tool to do generate the model as onnx.
currently, I need to turn to a data scientist to do my models, as I see no way to convert ML.NET model builder generated zip file to onnx.

**Comment by JakeRadMSFT** [comment]
Thanks for the recommendation! We'll look into what that would take!

**Comment by fuomag9** [comment]
> Thanks for the recommendation! We'll look into what that would take!
> 
> What issues are you hitting while trying to export ML.NET model to ONNX?

I'm probably not very knowdoledged (so please correct me on wrong stuff) on how ml.net training works, but from my experience reobtaining the tags, recreating the model instances and testing has to be done to correctly to export to onnx (I personally found it hard to find APIs for Ml.net for onnx conversion since they were deprecated/changed mutiple times and there was no obvious tutorial on how to do it). Having automated via the gui would be awesome and would allow people to save a lot of time for a task that seems automatable to me

**Comment by JakeRadMSFT** [comment]
@luisquintanilla Do we have any docs for ONNX export?
@michaelgsharp Can you point us to sample code?

**Comment by luisquintanilla** [comment]
We do in the API docs, but nothing in docs.microsoft.com. Here's a regression sample @briacht put together.

https://github.com/briacht/Regression-MLNET-ONNX

**Comment by michaelgsharp** [comment]
@r9guy the easiest way to convert the model builder zip file for now would be to load it as a normal ML.NET model and then use the `MLContext` to convert it to ONNX. There are still some ML.NET transformers that are not exportable to ONNX (though thats on our to do list), but I believe all the most commonly used ones are done.

```csharp
var loadedModel = mlContext.Model.Load("model.zip", out DataViewSchema modelInputSchema);
using (var stream = File.Create("model.onnx"))
     mlContext.Model.ConvertToOnnx(loadedModel, inputData, stream);
```

**Comment by toanlcgift** [comment]
I think modelbuilder should generate 2 outputs: .zip file & .onnx file. It is easier than converting from code.

**Comment by luisquintanilla** [comment]
Thanks all for the discussion. Closing this issue since it's already being tracked as part of #2059
