### ISSUE TITLE
Specific binary classification option

### ISSUE THREAD

**Issue by jpepg4** [dotnet/machinelearning-modelbuilder#1211]
**Is your feature request related to a problem? Please describe.**
Currently model builder treats all classification problems as multiclass even if the label for the data being provided is binary.  For whatever reason this doesn't seem to produce as good of model results as running it through the AutoML platform using a binary classification experiment.  Additionally running binary data as multiclass hides many of the useful metrics that get generated when running the binary classification experiment in AutoML

**Describe the solution you'd like**
Have a simple checkbox to indicate that your data is binary and should be run through a binary classification experiment

**Describe alternatives you've considered**
The current alternative is to build your own application based on using the BinaryClassification_AutoML sample or similar https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/BinaryClassification_AutoML

**Comment by LittleLittleCloud** [comment]
@briacht  for notification

After @beccamc 's proposal on ColumnDataType being implemented, we should be able to treat Multi-classification and Binary-classification differently through Advance Data option.

**Comment by beccamc** [comment]
@LittleLittleCloud You're saying if the data kind of the label column is bool we can automatically run binary instead of multiclass? I'm planning to make that change this week. Is this something you could on the backend add before we ship in March?

**Comment by beccamc** [comment]
@LittleLittleCloud Is this in the changes you've made for private preview? Or are we doing it later?

**Comment by LittleLittleCloud** [comment]
@beccamc No I haven't made any change related to this issue yet. But maybe I'll start soon

**Comment by LittleLittleCloud** [comment]
After model builder starts inferring the column with {0,1} as a numeric type instead of a boolean, all parts for this work has been completed and it is a good time to start this thread. Even though misformat label problem still exists, this problem is not that severe anymore because the most confusing part (label with 0/1 because false/true) is not the default behavior now. And the other parts (label with T/F, True/False => true/false) are not that confusing.

After this change has been made, there's still a way for users if they want to keep their label format in the output by change label type from boolean to string. And we should update in the doc that if label type is boolean, binary classification will be made and output label type will be boolean type too, which is a feature instead of a bug.

**Comment by luisquintanilla** [comment]
Created dotnet/docs#25922 to track and update docs accordingly.
