### ISSUE TITLE
Multi-process CPU training

### ISSUE THREAD

**Issue by andrasfuchs** [dotnet/machinelearning-modelbuilder#1219]
**Is your feature request related to a problem? Please describe.**
The training takes a lot of computing resources and most CPU have multiple cores. It would be great to benefit them fully, but for that to happen the training should be multi-threaded.

**Describe the solution you'd like**
I would like to train my models with the full power of my CPU, using all the cores.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/910321/107042496-219a2a80-67c2-11eb-8fee-4e8bddab2a7e.png)

**Comment by LittleLittleCloud** [comment]
Having trail running in separate process might help resolve #1531

**Comment by torronen** [comment]
@LittleLittleCloud The data file processing / reading CSV file would seem to be single-threaded. I think that is also what is happening in the screenshot because no models are tested yet. I believe it is not necessary because the order of observations can change.

I think you maybe changing the way the CSV file is being read, but if it is a longer process, a quick alternative might be to read and .ToDataframe() the CSV lines in a Parallel.For loop ?

**Comment by LittleLittleCloud** [comment]
tracking through #1565
