### ISSUE TITLE
GPU extension not installed while it's installed

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#1268]
![image](https://user-images.githubusercontent.com/16876986/108916654-6d7f0900-75e3-11eb-89fe-a472c3b7bd41.png)

**Comment by HaileyStorm** [comment]
I just submitted issue #1337 without realizing this issue already existed. It has a bit more detail. Here's a set of screenshots that includes the Extension Manager showing that the extension is installed:

![image](https://user-images.githubusercontent.com/55606304/112050086-10a93c80-8b16-11eb-8b23-8980d2ebed23.png)

**Comment by beccamc** [comment]
Thanks Hailey

**Comment by beccamc** [comment]
@LittleLittleCloud The issue seems to be that we can't load the GPU service in `AutoMLServiceFactory.CreateAutoMLServiceAsync`. The failure is _"Could not load file or assembly 'Microsoft.ML.ModelBuilder.AutoMLService.dll' or one of its dependencies. The system cannot find the file specified. (ErrorKind: Error HResult: 80131500)"_

I see that you changed the AutoMLService to an executable in [869](https://github.com/dotnet/machinelearning-tools/pull/869). Is this the problem? Do we just need to change it to .exe here? I've tried it locally and it can't find the .exe either. Am I on the right track?

**Comment by JakeRadMSFT** [comment]
Looks like the right track to me!

**Comment by LittleLittleCloud** [comment]
Might be!

**Comment by beccamc** [comment]
I changed the gpu service hub config... it didn't work but I just realized that I changed the root path too. Trying again now.

**Comment by beccamc** [comment]
@LittleLittleCloud I tried a few different combos and none worked... 
![image](https://user-images.githubusercontent.com/9122518/112550266-1c526880-8d8d-11eb-9991-8f45ce194197.png)

I also tried ... 
"assemblyPath": "Microsoft.ML.ModelBuilder.AutoMLService.exe",
"fullClassName": "Microsoft.ML.ModelBuilder.AutoMLService.ServiceFactory.AutoMLService"

Is there another place I need to change something? Do you remember from your previous work? Or was it just the exe change?

**Comment by LittleLittleCloud** [comment]
Any updates on the fix? @beccamc
