### ISSUE TITLE
Column To Predict enabled too soon

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1286]
Column to predict drop down is enabled while the data preview is still loading. No values are loaded yet. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/99eddf75-b7f1-4b52-b4e0-06e14bd01e13)

**Comment by beccamc** [comment]
If you change SQL tables the old column values are also available.

**Comment by vzhuqin** [comment]
Verify this issue on main branch: 16.5.25.2127002
1. The Column to predict is not enabled until the data preview is loaded
![1286.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/53027877-4bb8-4333-988f-61b4860358bf)

2. But if change SQL table ,the column to predict is disabled with old column's name instead of text "Select column", @beccamc could you help to confirm if this is expected?
![1286-2.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/fcfd58b9-9245-47f2-8c20-08707dec6fce)

**Comment by beccamc** [comment]
@vzhuqin Good catch. You're right, it should technically clear the name. However, I think this is low enough priority that we can close the issue as fixed.
