### ISSUE TITLE
Exception occured while exploring pipelines: Provided label column 'Sentiment' was of type String, but only type Boolean is allowed. System.ArgumentException: Provided label column 'Sentiment' was of type String, but only type Boolean is allowed.    at Microsoft.ML.CLI.CodeGenerator.CodeGenerationHelper.GenerateCode()    at Microsoft.ML.CLI.Program.<>c__DisplayClass1_0.<Main>b__0(NewCommandSettings options) Please see the log file for more info. Exiting ...

### ISSUE THREAD

**Issue by chandru2erode** [dotnet/machinelearning-modelbuilder#130]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/train
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rustd** [comment]
@chandru2erode can you please provide the following details?

**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by greazer** [comment]
@chandru2erode, can you at least supply the first few rows of the dataset you're using for sentiment analysis? I'm guessing the sentiment column is not 0 or 1. But rather something else. Currently there is a limitation of our sentiment analysis that supports only two sentiments.

**Comment by rustd** [comment]
@chandru2erode if this issue still reproduces, then please open a new issue with more details.

**Comment by bhrnjica** [comment]
I have this issue with Visual Studio Model Builder. 
Here is few rows of data:

```
Wow ... Volio sam ovo mjesto.	1
Kora nije dobra.	0
Nije ukusna, a tekstura je bila samo gadna.	0
Zaustavio se tokom bankarskog odmora krajem maja, na preporuku Ricka Stevea i svidjelo mu se.	1
Izbor na meniju je bio velik, kao i cijene.	1
Sada se ljutim i želim svoj prokleti fos.	0
Honeslty nije okusio taj svjež.)	0

```

**Comment by oneEyedSunday** [comment]
This could have been caused by a stray newline. 
If this was the case, you could 
```cs
csv.GetField("text").Replace(Environment.NewLine, " ")
.Replace("\r\n", " ")
.Replace("\n", " ")
.Replace("\r", " ")
```

with any other combination of likely carriage return delimiters
