### ISSUE TITLE
Advanced data options takes 3 clicks

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1316]
I have to click three times to change the Column Purpose and Data Type

**Comment by beccamc** [comment]
Reverted back to old UI

**Comment by beccamc** [comment]
From "Model Builder Bug Bash - Take 2"

Jake Radzikowski
2/23/2021 5:07 PM
I agree -  it's a bit hard to tell it's editable

Rohan Malpani
2/23/2021 5:07 PM
Bri, I haven't reached Advanced data options yet. I will play around with it a bit. From your screenshot, it does look quite simple. 

Jake Radzikowski
2/23/2021 5:08 PM
I think Becca said there was still some styling stuff to do 

Becca McHenry
2/23/2021 5:14 PM
Right now we're using the default DataGrid as WPF designed it. We can make changes to that, and I can do customizations that change it back to what it looked like. I want to know if we're happy with the new layout before I make those changes. 

Bri Achtman
2/23/2021 5:17 PM
I think so yeah!

Rohan Malpani
2/23/2021 5:19 PM
Sorry Becca, won't be able to give you my feedback on Adv. data options dialog right away. I still have to play around with it. Will keep you posted. 

Becca McHenry
2/24/2021 12:25 PM
Bri Achtman We definitely aren't happy with the combo boxes in the Advanced data options, right? You want them to be editable/enabled right away (not have to click on them) 
I'm asking because I have an accessibility issue that depends on the implementation, so knowing which path we want to take will help me know if I need to fix the accessibility issue or not 

Jake Radzikowski
2/24/2021 12:26 PM
What are the trade-offs?
Is it possible to get the regular drop down experience in the data grid?

Rohan Malpani
2/24/2021 12:27 PM
What is the accessibility issue, Becca?

Becca McHenry
2/24/2021 12:27 PM
Yes is it possible to get the regular drop down experience in the data grid, but I need to write it as custom controls. Shouldn't be a big deal as we were doing something similar before

Becca McHenry2/24/2021 12:28 PM
Accessibility issue is a bug in WPF combo box, I can forward you the email with details if you're interested
The advantage of the current UI is that nothing is custom. WPF handles rendering, accessibility labels, and sorting columns. If we do our own we need to write and maintain more code. Need to ensure our custom accessibility names make sense in screen reader. We lose the built in sort functionality. 

Jake Radzikowski
2/24/2021 12:35 PM
I think we should do the custom control -
 
Like Bri said - "it's not immediately obvious that you can change column purpose / data type" which is the main thing we want them to do
😕
 
I wish the DataGrid had more obvious editable things without customizing it
😕

Rohan Malpani
2/24/2021 12:37 PM
Could we show the drop arrow on-hover or on-keyboard focus of that cell? 

Jake Radzikowski
2/24/2021 12:39 PM
For me it's the 3 or so clicks it takes to get the drop down to actually show up

Rohan Malpani
2/24/2021 12:40 PM
How 3?

Jake Radzikowski
2/24/2021 12:41 PM
For me it seems like it's - 
click to select row/cell,
double click to bring up drown down

Rohan Malpani
2/24/2021 12:42 PM
got it.  

Rohan Malpani2/24/2021 12:42 PM
Okay, I finally got to play with it and I see the problem.

Rohan Malpani2/24/2021 12:43 PM
Could we take a step back here and rethink of how we are doing this grid? 
The overall approach is good - it is simpler, and easier to understand all the properties associated with individual items. But the interaction seems to be a bit off. 

Becca McHenry
2/24/2021 1:01 PM
Rohan Malpani Do you have a few minutes to chat? 

Rohan Malpani
2/24/2021 1:01 PM
I do have a stand up right now but may be right after? 
I can ping you when I am free?
