### ISSUE TITLE
Can change name of column in Advanced Data Options

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1317]
If I double click on the name in Columns column, I can change the name

![image](https://user-images.githubusercontent.com/10437687/110365822-59cb9d80-7ffa-11eb-82c0-29507a90315e.png)

If I change the name here, I get this error which I have to close out of SEVEN times (I'm guessing for the number of columns in the dataset):
![image](https://user-images.githubusercontent.com/10437687/110365885-6bad4080-7ffa-11eb-97ff-49d3cc325686.png)

**Comment by vzhuqin** [comment]
Validate this issue on Main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
@beccamc As I can't access https://app.zenhub.com/workspace/o/dotnet/machinelearning-tools/issues/973
 to get reference information. Could you help to confirm whether the expected result is don't allow change the column name in advanced data options dialog?
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b9d73276-6b67-40fa-a0ed-dfec3fb286c7)

**Comment by vzhuqin** [comment]
Reference: https://github.com/dotnet/machinelearning-tools/pull/973, 
This issue is fixed on:
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122301
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

**Comment by beccamc** [comment]
Yes, the above is the expected result! This is fixed.
