### ISSUE TITLE
Set up CLI suggestions (tab-based auto-completion) doesn't work.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1404]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- dotnet-suggest: 1.1.221601
- .Net: 5.0.201
- MLNET: 16.2.0

**To Reproduce**
1.After install tool ML.NET CLI, on PowerShell, run below:
dotnet tool install dotnet-suggest -g
echo $profile
2. Copy the contents of dotnet-suggest-shim.ps1 to myPowerShell profile;

**Expected behavior**
Set up CLI suggestions (tab-based auto-completion) can work.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/115217843-7a7a2d80-a138-11eb-95ca-cecbac73e83e.png)

**Additional context**
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-ml-net-cli

**Comment by vzhuqin** [comment]
The doc was removed from the original https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-ml-net-cli , could someone provide the new docs to verify?

**Comment by luisquintanilla** [comment]
@LittleLittleCloud after the dotnet-suggest updates merged, what are the setup instructions (if any) to get this working on the CLI? Is it the same as the instructions that were removed from the doc?

---

## Set up CLI suggestions (tab-based auto-completion)

Since the ML.NET CLI is based on `System.CommandLine`, it has built-in support for tab completion.

An example of how tab auto completion works is shown in the following animation:

![image](./media/cli-tab-completion.gif)

'Tab-based auto-completion' (parameter suggestions) works on *Windows PowerShell* and *macOS/Linux bash* but it won't work on *Windows CMD*.

To enable it, in the current preview version, the end user has to take a few steps once per shell, outlined below. Once this is done, completions will work for all apps written using `System.CommandLine` such as the ML.NET CLI.

On the machine where you'd like to enable completion, you'll need to do two things.

1. Install the `dotnet-suggest` global tool by running the following command:

    ```dotnetcli
    dotnet tool install dotnet-suggest -g
    ```

2. Add the appropriate shim script to your shell profile. You may have to create a shell profile file. The shim script will forward completion requests from your shell to the `dotnet-suggest` tool, which delegates to the appropriate `System.CommandLine`-based app.

    - For bash, add the contents of [dotnet-suggest-shim.bash](https://github.com/dotnet/System.CommandLine/blob/main/src/System.CommandLine.Suggest/dotnet-suggest-shim.bash) to `~/.bash_profile`.

    - For PowerShell, add the contents of [dotnet-suggest-shim.ps1](https://github.com/dotnet/System.CommandLine/blob/main/src/System.CommandLine.Suggest/dotnet-suggest-shim.ps1) to your PowerShell profile. You can find the expected path to your PowerShell profile by running the following command in your console:

    ```console
    echo $profile
    ```

(For other shells, [look for](https://github.com/dotnet/System.CommandLine/issues?q=is%3Aissue+is%3Aopen+label%3A%22shell+suggestion%22) or open an [issue](https://github.com/dotnet/System.CommandLine/issues).)

**Comment by LittleLittleCloud** [comment]
@luisquintanilla 
Yes, the setup step is identical with previous cli.

https://github.com/dotnet/command-line-api/blob/main/docs/Features-overview.md#Suggestions

**Comment by luisquintanilla** [comment]
Great. Thanks
