### ISSUE TITLE
Ocotpus training fails for wrong column type

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1444]
**Model Builder Version**: main branch

**Bug description**: 

**Steps to Reproduce**
1. Select Value Prediction training
2. In column to predict, select a string value (in taxi dataset, vendor_id)
3. When using AuoMLType Octopus, the dataset reports a failure, but doesn't stop training 
4. Even after cancelling, it appears that training is still running (error messages continue to print). See gif below where I have previously hit cancel (button text has changed and countdown isn't continuing), but we're continuing to train

**Expected Experience**
Two problems to fix here...
1. If there is an error we shouldn't continue training 
2. When I click cancel, we should actually cancel

![ocotpus.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/7697e734-a2fe-40c1-8c49-19a3b2251452)

**Comment by beccamc** [comment]
Stack trace:

**Comment by LittleLittleCloud** [comment]
After a close look at, the cancellation token actually works in Octopus, it's just there's too many outputs so it takes a while until the training process is canceled. And after it's canceled, there's no new log to the output except those old ones. But there are too many so the logging process will still go a long time until all logs being printed. However, in release mode, where there's much fewer logs being printed to the output window, the cancel button will respond pretty quickly.

So strictly speaking, it's more like a gem of too many logs which slows down the system, where the logs are mostly error messages and stacktrace from exceptions throw by trials. In the situation where there's user data error (like label mistyping), each trial will fail really fast and since Octopus won't stop on trial failure (because a trial can fail for various reasons, some are recoverable while some are not. So it's unwise to brutally kill the entire training because of one single trial failure. However, Octopus is not smart enough to distinguish which error is recoverable so ... shrug). it will keep kicking off new trials which also fail immediately and throw exceptions plus tons of logs, which slows down model builder. As for now, all logs from fail trials are debug level so it won't show in release mode, which means in release channel there will be no output in such error and it's another bug that needs to be fixed.

To fix this, I would suggest 1) set error messages to `info` level so user can see trial error in release mode. and 2) try to differentiate unrecoverable error and fail immediately in those cases. Unrecoverable errors include mostly data-related error and there'll be a lot of edge cases. But we can at least start collecting them.

**Comment by vzhuqin** [comment]
This issue not occurs on main branch: 16.5.25.2126901
No error during training.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/96efad05-0266-427f-b93a-830c17721900)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/5a7405fb-0f2b-49af-aa79-9889a606896a)
