### ISSUE TITLE
Data should not be lost even if switch between File and SQL Server type.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1450]
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

**Main branch:** 
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Recommendation scenario;
5. Select Local (CPU) environment;
6. Navigate to Data page: select File type and add data, save setting in advanced data options dialog;
7. Save the mbconfig file;
8. Still on Data page: switch to SQL Server type, then select back to File type;
9. See error: the data saved just now is lost.

**Expected behavior**
Since the data has been saved, it should not be lost switching between File and SQL Server type.

**Screenshots**

![datalost3](https://user-images.githubusercontent.com/81727020/117777225-fb77a100-b26e-11eb-99c5-6d1d6511ab31.gif)

**Comment by beccamc** [comment]
@vzhuqin I see why this is confusing, however this is by design. We're considering changing the data source to be the same as "going back" in the wizard (similar to losing your progress if you change environment or scenario). For now, it is expected behavior that going from File -> SQL -> File will reset progress. 

Let me know if you have questions!
