### ISSUE TITLE
Has header change in advanced data option does not  change/reset label column 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1480]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. select Value prediction
2. Load Taxi_fari dataset
3. Complete all the tabs
4.  Back to the data page  and got to advanced options
5. Change  header  and save

**Expected Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/bf6113b1-208f-4640-9352-a1e6acc53ae6)

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/3bff81e2-8cd2-4821-aed5-0afe77a4d1ac)
**Additional Context**
Even the user is not able to choose the correct label column

**Comment by andrasfuchs** [comment]
I can confirm that the header update works in v16.9.2.2205603. 👍 
It would be nice if after changing the header setting to yes, it would try to re-detect the data type of the columns, because it is possible that the headers were detected as `String`s, but the actual values are `Single`s.

![image](https://user-images.githubusercontent.com/910321/148769256-a9b08576-075e-4595-a721-25234f07e8e4.png)

**Comment by beccamc** [comment]
@andrasfuchs it should re-detect after the header change. I see that it hasn't in your case, and that it's pretty tedious to change by hand. I think you've shared this dataset with us before, but can you share it again?

Also, you can open the .mbconfig file in Notebook and do a find and replace on those "String" values to quicky update them all.

**Comment by andrasfuchs** [comment]
Sure, here it is: https://drive.google.com/file/d/1C2Of2UIHN2y7l5J-SvEvacFhTAHMCCcm/view?usp=sharing
