### ISSUE TITLE
The results should not be predicted without data on the "Evaluation" page. 

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1544]
**System Information (please complete the following information):**
- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.6.1.2132901 (Main Branch)
- Microsoft Visual Studio Enterprise 2019: 16.10.2
- .Net: 5.0.301

**Describe the bug**
- On which step of the process did you run into an issue: Evaluate page
- Clear description of the problem: can predict the result with empty data, this issue appears on Text classification and Value prediction scenarios, not happen on Recommendation scenario.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window.
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. After trained;
5. Navigate to Evaluate page, delete the sample data, then click the "Predict" button, can get the predicted result, this is very strange.

**Expected behavior**
Should not predict the result if there is no data on Evaluate page, it is recommended to pop up a message to remind user when predicting the result without data.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/123930453-594c7d80-d9c2-11eb-9f7e-8f53d6850dab.png)

**Additional context**

**Comment by torronen** [comment]
This is a good point. I think it also relates to the consumption of models. It is a very easy (and risky) mistake to run a model without providing it the data it needs. As a personal example, I had a pricing AI many years ago which gave prices every time. Because some users tend to be lazy, some users just kept clicking "Make price" without providing any additional data. It created huge pricing errors.

But I also think there may be cases where we want to run the model even if not all data is available, such as, to give some additional insights for expert users who understand the impact of missing data.

So perhaps, the ML model should have a bool ValidateInput(ModelInput model) method to check the model has all fields set? Then that could be run on this pge Evaluate page.

BTW, I've seen in some cases the model creation failed, and this page helps to check the model can at least be run. If there is large number on inputs, it would be best to let run the evaluation even if there is no data available. This page is not very good for evaluation in many cases because it is slow to use if multiple inputs are required (such as taxi fare example).

**Comment by beccamc** [comment]
@briacht Can we get your thoughts here?

**Comment by briacht** [comment]
I think it's fine to leave as is. If you train a model with the API and then create a new model input to predict without setting the properties, you'll still get a result.

We could add a warning - something like "You left this input blank which will affect the model results." - @romalpani thoughts?

We should look into inference perf on this step though - "This page is not very good for evaluation in many cases because it is slow to use if multiple inputs are required (such as taxi fare example)" -- thanks for your feedback @torronen

**Comment by beccamc** [comment]
@torronen, regarding your feedback on "This page is not very good for evaluation in many cases because it is slow to use if multiple inputs are required (such as taxi fare example)."  Did you mean the perf is bad, or did you mean it's slow to manually add data? Thanks!

**Comment by torronen** [comment]
@beccamc Slow to manually add data, because it would be best to try at least 10 different observations. Not sure if it is a good idea but if it had a "next" button to iterate through the test data AutoML used, that would make it easier to make at least a quick sanity test.

**Comment by beccamc** [comment]
Moving this to "Needs design" as we have a few questions for @romalpani

**Comment by beccamc** [comment]
Closing in favor of https://github.com/dotnet/machinelearning-modelbuilder/issues/2101
