### ISSUE TITLE
Move Test Data Sets to Blob Container

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#155]
**Describe the bug**
Datasets that we test against currently live on a fileshare but it's not recommended to access fileshares from build machines.

**Comment by JakeRadMSFT** [comment]
Closing for now. We'll re-evaluate what to do for our tests.

**Comment by justinormont** [comment]
If you do move them to a blob container, I'd recommend:
aka.ms link => Azure CDN => Azure Blobstore

This is the form used in `ML.NET` tests, and allows for moving the datasets in the future without breaking the building of old versions of the codebase. For example if you want to look for regressions over time. The CDN is to keep the build speed (and [benchmarks](https://github.com/dotnet/machinelearning/blob/365ccf292789ba1f14d80b13e44daaf951517fff/test/Microsoft.ML.Benchmarks/README.md)) fast as it otherwise waits on the blob store download due to the build server being cleaned between each build.
