### ISSUE TITLE
Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#1561]
**Bug description**
After starting training, I receive error "Array dimensions exceeded supported range."

**Steps to Reproduce**
1. Create CSV dataset with high number of rows
2. Create a classification task and start training

**Expected Experience**
Training should start and run normally,
OR, error should tell me if I want to continue by skipping exceeding values
OR, error should tell me what is the max value and is it about columns, rows, or the values

**Actual Experience**
Before any iterations started, the error in the below file was received
[a7d2d18c-6192-4958-8487-704e46d05c60.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6763513/a7d2d18c-6192-4958-8487-704e46d05c60.txt)
<img width="538" alt="Capture" src="https://user-images.githubusercontent.com/26261427/124457728-cbdba580-dd94-11eb-8016-b3eb17659237.PNG">

**Additional Context**
Big dataset (750 gigabytes). Server RAM 1 TB with 4TB+ free disk space.

**Comments**
I dont know if the problem is the large number orf observations, but if it is:
Machine Learning tasks should primarily work with high number of observations
If not, we should receive error telling what the maximum limit. Documentation should also inform us about the hard limit for number of rows. Ideally, Model Builder could ask if I want to proceed by skipping the  observations which are above the max limit, and ignore rest of them (so I dont need to edit my dataset)

**Comment by torronen** [comment]
If it is about a hard limit on number of observations, what would be the max?

**Comment by torronen** [comment]
The "Data" step in the wizard already counts the rows and columns. Perhaps this page could already warn me if I exceed the supported range? 

Even better if it would allow me to skip any rows past the limit (skip randomly best, but skip from the end is ok ay too). If I understand correctly Model Builder creates a temporary copy of the dataset so perhaps it could be implemented fairly easily.

![kuva](https://user-images.githubusercontent.com/26261427/124459900-5ae9bd00-dd97-11eb-8355-f5f84b202c75.png)

**Comment by LittleLittleCloud** [comment]
Hi @torronen 

Sorry to see you hitting this issue, you might be the first one to hit this bug. The bug is from ML.Net DataFrame. but your issue also let us re-thinking if it is the right way to convert the intermediate dataset into Dataframe to run sampling strategy before training simply because its APIs are easier to use, which turns out to be a bad idea when the dataset is huge. 

As a temporary fix, converting back to IDataView API during resampling so the dataset is streamlized should solve this issue. We will continue following the related issue you raise on machinelearning repo, thanks for the feedback.
