### ISSUE TITLE
"Click Predict to see the predict result" text should not display after the user clicked predict button  in evaluate page

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1581]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/36615490/125144088-9951e580-e0d1-11eb-912a-64ac947771ea.png)

**Additional context**

**Comment by zewditu** [comment]
,@romalpani, And I think the predict button has to be disabled while prediction is in progress.

**Comment by romalpani** [comment]
@zewditu Yes! And we should have a spinner next to it while prediction is going on (same as Train).

**Comment by zewditu** [comment]
@romalpani  sounds good! And that might also need to change the place where to displat the  prediction result .

**Comment by zewditu** [comment]
@romalpani   I think do we need to prompt the user to  click predict button when the tryout value is changed after the user makes the first prediction, 
if yes do we need still to say " Click predict to see predicted result" or something else?

**Comment by vzhuqin** [comment]
Verify this issue on latest main build: 16.7.2.2142301
For Data classification, Value prediction:
1. The text "Click Predict to see the predict result" is not display after clicking "Predict" button;
2. The "Predict" button is disabled while predicting;
3. There is a spinner under "Results" during predicting.
![1581 fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/856d7193-9480-4038-86c7-b2a716cef048)

**Comment by vzhuqin** [comment]
But I found other issues on Recommendation, Image classification, could you help to take a look?

**Recommendation**
The spinner above predicted rating should not be displayed since it already has the result.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/91cfee03-2aff-4706-95e1-2f9a0f011085)
**Image classification**
The spinner shows too early, it should be displayed after loaded the image, rather than appearing as soon as click the "Browse an image" link. 
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/8967418a-789c-4c95-964a-a9ee06376312)

**Comment by vzhuqin** [comment]
Not repro this issue on main: 16.9.1.2155901
Recommendation:
![Recomm_fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/e67c132e-f379-481d-ad17-7b1af4aa0753)
Image classification:
![1582image fixed.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3d40df75-00db-4d2c-9d69-4c7ba57d2cd9)
