### ISSUE TITLE
Property X is missing the LoadColumnAttribute attribute / ModelInput should have [LoadColum(0)] attribute

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#1618]
**System Information (please complete the following information):**
 - Model Builder Version:  16.6.2.2133003
 - Visual Studio Version: 16.10.3

**Describe the bug**

Trying to retrain manually with generated ModelInput and .training file raises exception "Property X is missing the LoadColumnAttribute attribute' "

Current generated ModelInput.cs does not have the LoadColumnAttribute
![image](https://user-images.githubusercontent.com/26261427/126160947-393ffcff-23d6-45dc-855a-4cb4ebf529bf.png)

One of my older models (where ModelInput.cs is a separate file), and e.g. issue  623, has a sample with LoadColumnAttribute present. Is the LoadColum(0) intentionally removed, and there is a better way to load the CSV to the IDataView?

Given PR related to issue https://github.com/dotnet/machinelearning/issues/4480 was not merged, and ML.NET [CSV documentation tells to use LoadColumn[]](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net#annotating-the-data-model-with-column-attributes) so I assume it is probably still needed. ( Completion of https://github.com/dotnet/machinelearning/issues/4480 would be a nice addition if there is not any other way yet )

**To Reproduce**
Create a new model, and read the CSV to an IDataView for manual retraining
```
  IDataView data = mlContext.Data
                .LoadFromTextFile<MyModel.ModelInput>(
                @"Q:\xyz.csv", 
                separatorChar: ',', hasHeader: true, true, true, false);
```

**Additional context**
CSV file with headers

**Workaround**
Read first to in-memory collection, then to IDataView
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net#load-data-from-other-sources

This might not be ideal for large datasets, and would not allow streaming from file.

**Sub-issues**
The ColumnName attribute currently makes the first letter uppercase. In the example photo "dtHour" becomes "DtHour". ColumnName annotation probably should keep the original value from the CSV even if properties would follow general C# naming guidelines.

It would be a good idea to make this file generated based on a user editable template, because users might need to add additional annotations, such as for the chosen CSV parser. For example, for the workaround above with CSVHelper [Name] annotations are needed.

**Comment by zewditu** [comment]
@JakeRadMSFT, @LittleLittleCloud  for visibility.

**Comment by LittleLittleCloud** [comment]
> Sub-issues
The ColumnName attribute currently makes the first letter uppercase. In the example photo "dtHour" becomes "DtHour". ColumnName annotation probably should keep the original value from the CSV even if properties would follow general C# naming guidelines.

Thanks for the suggestion, and there might be a specific reason behind the capitalized first letter. (@briacht who might knows), which is, based on my guess, is it's not always possible to keep property name along with csv header because some of original column name might be illegal in C# syntax. But it's possible to always transfer column name to something that both match C# syntax and C# name guideline.

> Trying to retrain manually with generated ModelInput and .training file raises exception "Property X is missing the LoadColumnAttribute attribute' "

@briacht maybe add that attribute back in next release? I don't know why we remove it, maybe just by mistake.

@torronen In the meanwhile, maybe try `DataFrame` API which can load from csv without schema defined as a work-around? I know `DataFrame` has some bugs with large dataset so this might not work for you, but they recently did a new release(1.5.6) which *might* contains the fix for your issues. 

![image](https://user-images.githubusercontent.com/16876986/126205349-70ad433e-905c-43da-9870-10b13c0cc401.png)

**Comment by torronen** [comment]
@LittleLittleCloud Thanks I'll try that. 

If you will discuss casing, take note .training.cs keeps the original ones. 
![image](https://user-images.githubusercontent.com/26261427/126209800-ceaf2d8f-f488-4145-8d54-7e33d63512b8.png)

I mention it because I have some issue with casing on the workaround in the original post.  
![image](https://user-images.githubusercontent.com/26261427/126211843-cee98580-59a2-407c-8c02-011fa24aebda.png)

`List<MyModel.ModelInput> records = ReadFromCSV();
IDataView data = mlContext.Data. LoadFromEnumerable<MyModel.ModelInput>(records);`
It raises this exception:
![image](https://user-images.githubusercontent.com/26261427/126211868-51b90d95-e14d-498f-9ca5-e877cb978b90.png)
If i update `dtIsPublicHoliday `to `DtIsPublicHoliday` then I get the exception in only the next field and this first one passes.

It's not a big issue, I will update CSV to capital starting letter, and try your workaround until then.

**Comment by torronen** [comment]
@LittleLittleCloud DataFrame.LoadCSV works perfectly, thanks!

**Comment by zyzhangyh** [comment]
We need specify"LoadColumn" ,like this:
public class ModelInput
 {
            [LoadColumn(0)]
            public float Column1 { get; set; }
}

**Comment by beccamc** [comment]
We've added LoadColumn attributes back in for the next release.

**Comment by beccamc** [comment]
This fix has shipped! Please install the latest version of Model Builder [16.14.0](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022) to see the change. 

LoadColumn attributes are now included in the generated code.
