### ISSUE TITLE
Version number is included in every object

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1651]
Not sure if this is "by design at this point"... I may have missed this in a PR review. I don't think we should include a version number in each object. 

Although this column data type may not be changed in version 2.x of the mbconfig (e.g. MBConfig version is 2.x but we haven't modified ColumnDataType since version 1) we should infer this from file version number. IMO adding version number to each object creates bloat. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/afbbef89-73d0-4c8c-a51c-9ac4f8add1db)

**Comment by LittleLittleCloud** [comment]
@beccamc 

This is by design in order to avoid reimplement all child schemas once the parent schema is changed. Or avoid changing the parent schema for every child schema change.

**Comment by beccamc** [comment]
I would argue we should change the parent schema version for each child schema change. If we add a new property to ColumnProperties we increment the file version. I'd expect it to work similarly to a rest api, a breaking change to any part is an incremented version of the whole file.

**Comment by LittleLittleCloud** [comment]
Although we use "parent" and "child" to differentiate schemas in different levels, on the code level, they are treated like the same. And that's the philosophy of the entire schema-based update path, which greatly simplifies the migration process when a schema contains a nested schema: a migration handler only needs to deal with depth = 1 properties, and leaves the migration work to other handlers for all other properties with depth > 1. And it also simplifies how a schema looks like in code level: all properties in schema shall be either primitive type or `MBConfig`, which indicates a nested schema, and all schema shall be 1-depth only. It's a bit like Json, in which values can only be a primitive type, another json object or an array of any of the previous one.

In this case, both the `Version` and `Type` are used to locate a schema. This is necessary because in the nested schema case, the parent schema doesn't save any type information of its nested schema. This characteristic requires the loader to find the right schema instead when loading. And that's what `Version` and `Type` are used for. Without `Version`, it will be difficult for the loader to find the right schema because `Type` might be shared among schemas**. The `Version` in this circumstance, is schema version rather than traininig configuration version**, and it's likely that a parent schema with `Version 2` has a child schema with `Verson 1`.

**Comment by beccamc** [comment]
Okay, I've come around to being okay with this.  Based on what you've said, I am wondering if we could make one change.. 

> We can remove version if each schema has an identical type

Does this mean we could remove "version" from the column properties? It seems like a lot to have the version number in hundreds of columns.

**Comment by LittleLittleCloud** [comment]
> Does this mean we could remove "version" from the column properties? It seems like a lot to have the version number in hundreds of columns.

If so we need to put version info in column info type, as there's more than one schema for column properties

**Comment by beccamc** [comment]
Sorry, I didn't get what you mean by that. Is it possible for it to look like this?

"DataSource": {
    "Type": "SQL",
    "Version": 1,
    "ColumnProperties": [
      {
        "ColumnName": "Id",
        "ColumnPurpose": "Ignore",
        "ColumnDataFormat": "String",
        "IsCategorical": false,
        "Type": "Column",
      },

**Comment by LittleLittleCloud** [comment]
Kinda, except a small version suffix will need to be added to ColumnProperties

```
"DataSource": {
"Type": "SQL",
"Version": 1,
"ColumnProperties": [
{
"ColumnName": "Id",
"ColumnPurpose": "Ignore",
"ColumnDataFormat": "String",
"IsCategorical": false,
"Type": "Column_V1",
},
```

**Comment by beccamc** [comment]
Okay, maybe this isn't worth it and should just be left as is?

**Comment by LittleLittleCloud** [comment]
@beccamc 

I think so, however in the future if we are really confident that ColumnProperties class won't be changed we can also remove the version (and even type) info by making it a concrete class in datasource schema

**Comment by beccamc** [comment]
Great! I will close this
