### ISSUE TITLE
There is no training results after training complete.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1668]
**System Information (please complete the following information):**

- Windows OS: Windows-10-Enterprise-21H1
- ML.Net Model Builder (Preview): 16.7.2.2140201 (Main Branch)
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 2.1
- .Net: 5.0.302

**Describe the bug**
- On which step of the process did you run into an issue: Train and Evaluate pages
- Clear description of the problem: 

**To Reproduce**
1. Select Create a new project from the Visual Studio 2022 Preview start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select text classification scenario to complete the training;
5. See error: 
- there is no Training results on Train page.
![image](https://user-images.githubusercontent.com/81727020/127970977-f3f6345a-6a48-4d37-ba51-38b6b2f2d8e3.png)
- no show the result of Best model on Evaluate page.
![image](https://user-images.githubusercontent.com/81727020/127971599-227f65c3-203a-4d26-b07e-a612e0634f22.png)

**Expected behavior**
Show the training results and best model on Train and Evaluate pages after training complete.

**Additional context**
Re-open model builder after training complete, not see this issue.

**Comment by beccamc** [comment]
Thanks Qin! I made a new label - VS2022 for bugs from the 2022 build. Can you start adding that label to 2022 bugs?

**Comment by vzhuqin** [comment]
This issue also appears on Microsoft Visual Studio Enterprise 2019: 16.10.4 with 16.7.2.2140201 (Main Branch).

**Comment by beccamc** [comment]
Took a quick look, `SetBestAlgorithm()` is never being called in TrainViewModel. Looks like the `TrainSession_OnAlgorithmIterationEvaluatedEventHandler `never sends an `AlgorithmIterationEventArgs `marked IsBest

**Comment by beccamc** [comment]
So the problem here is the "IsBest" flag isn't getting passed from the AutoML process back to the Model Builder process. 

Here is the OnAlgorithmIterationEvent in the AutoMLEngine.cs file. It is invoking the AlgorithmIterationCompleted event with `IsBest = true`
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/03554310-2c11-4665-9ee9-323490c37720)

On the ModelBuilder side, in TrainSession_OnAlgorithmIterationEvaluatedEventHandler the AlgorithIterationEventArgs have IsBest = false
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/ffadee82-3051-4ec1-b27d-0b9b1d54bb0a)

Is this just a serialization problem? You can see the properties of the [AlgorithmIterationEventArgs ](https://github.com/dotnet/machinelearning-tools/blob/main/src/Microsoft.ML.ModelBuilder.AutoMLService.Contract/AlgorithmIterationEventArgs.cs)aren't sent, while the inherited Trial properites are sent. We didn't used to have this problem (I assume the change came with Xiaoyun's change [here](https://github.com/dotnet/machinelearning-tools/commit/ff6aacab9af1601519bb0f1fd716d3a51e7bd64f#diff-dc139117a7a622f7ee7cde7dc31297414c07c7a369b1ea847b68cce73114cfc2))
