### ISSUE TITLE
Spam/ham fails via CLI

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1672]
I'm guessing the problem is that it's "boolean" classification, but using spam/ham instead of true/false or 0/1. 

From the [Log file](https://app.zenhub.com/files/186917455/e55332a2-7093-43fe-a9cc-5d5a1bc33a13/download):
2021-08-03 17:37:55.2373 DEBUG System.FormatException: String ' available trainer: LGBM, RF, FASTTREE, LBFGS, SDCA ' was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.Boolean.Parse(String value)

[Spam dataset](https://app.zenhub.com/files/186917455/2fdec184-c809-4b5c-b62a-9b417b26c5e2/download)

**Comment by beccamc** [comment]
@LittleLittleCloud FYI on this issue.

**Comment by LittleLittleCloud** [comment]
It's something related to feature flag, I'll fix this.

**Comment by LittleLittleCloud** [comment]
The error `2021-08-03 17:37:55.2373 DEBUG System.FormatException: String ' available trainer: LGBM, RF, FASTTREE, LBFGS, SDCA ' was not recognized as a valid Boolean.` is not fatal. It will just causes FF manager to return false and disable functions.

The fatal error is in data processing, where the dataset's header is determined as "false" by prose while it's true. However even setting `--has-header=true` doesn't resolve this. I believe it's because mlnet(or dataProcessing engine) doesn't respect that flag for some reason.

Meanwhile, model builder also can't train that dataset. Firstly, it shows that the dataset has 5 columns while it only has two. And after setting header flag to true, it still shows 5 headers and throws "An item with same key has already been added" somehow. And training also fails.

![image](https://user-images.githubusercontent.com/16876986/137802620-33a314dd-ba96-4dbe-b2ff-cec431aa0987.png)

**Comment by LittleLittleCloud** [comment]
@beccamc Can you fix this in model builder side and I'll take over mlnet.cli side

**Comment by vzhuqin** [comment]
@beccamc Still have model builder error: An item with the same key has already been added. on ML.Net Model Builder: 16.9.1.2155901 (Main)
Column Headers: No
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/28bfd627-88ad-4c89-8423-6396e7bd31c5)
Column Headers: Yes
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b02402e5-85cb-4645-bb5f-33dbda0e06e9)

Not repro this issue on mlnet: 16.9.2
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0b74390a-86e2-4770-9770-cedc4d122ae8)

**Comment by beccamc** [comment]
The problem here isn't the spam/ham thing, but that there three empty columns. 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/f2e3f34a-1df1-43db-ac62-303dfac6c89f)

**Comment by beccamc** [comment]
Two things to verify... 

1. As stated above the issue isn't actually with the spam/ham data. The problem is that the spam dataset linked has empty columns. PR 1347 adds an error message that makes a bit more sense. Note that for this dataset, the column name will be empty in the error message (it will say "Please remove or rename column .").  I think this is enough info for the customer to open their file, or enough info for us to figure out the problem. 

![image](https://user-images.githubusercontent.com/9122518/142664455-0a9c3e7b-6beb-4e09-9163-f24186261fb1.png)

2. A spam/ham dataset without the extra columns works fine. See attached file [spam2.csv](https://github.com/dotnet/machinelearning-modelbuilder/files/7571876/spam2.csv) for testing.

**Comment by vzhuqin** [comment]
Verify this issue on latest main: 16.9.1.2160801
For "**Column Headers: Yes**": Will note that "Cannot have multiple columns with same name. Please rename or remove column."
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4f00085a-8197-412b-810d-ad94b0437424)

For "**Column Headers: No**" and "**dataset without extra columns**", can complete training.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/4abc0fdb-2476-4c46-9404-3936cd9db524)

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/0915c087-0c17-4e1a-8337-13a0021278ea)
