### ISSUE TITLE
Accessing resnet files takes a lot of time 

### ISSUE THREAD

**Issue by AmritanshuAVerma** [dotnet/machinelearning-modelbuilder#1691]
We should let the system target a local resnet source if present

![image](https://user-images.githubusercontent.com/40417442/129306028-aae70f5a-288c-48c8-b4f9-e433835e5a59.png)

**Comment by AmritanshuAVerma** [comment]
[Source=AutoML, Kind=Error] [Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Error] resnet_v2_50_299.meta: Download timed out

**Comment by zewditu** [comment]
@AmritanshuAVerma  usually this error happens for small datasets. when closing the error window what do you see?  How large is your dataset?

**Comment by zewditu** [comment]
@AmritanshuAVerma  what do you want to do? is this image classification or any you want to do any non -image classification task?

**Comment by AmritanshuAVerma** [comment]
It was a small dataset for image classification with 400 images each in 2 categories. it worked after 4 attempts. I am not sure how.

**Comment by zewditu** [comment]
I think the screenshot of the error window is not for image classification because we do not have the training time we set for image classification. This error window is for text classification scenarios with a small dataset.  

For image classification for a small dataset(< 5 images per class ) we have a warning message on the data page.

@LittleLittleCloud  do we have  an error message for a small dataset in Image classification?
