### ISSUE TITLE
Model Builder GPU is not worked

### ISSUE THREAD

**Issue by dmamel** [dotnet/machinelearning-modelbuilder#1770]
Model Builder GPU is not worked

![image](https://user-images.githubusercontent.com/45320291/132105469-93b7128f-d55f-48de-831b-2f450040ec13.png)

![image](https://user-images.githubusercontent.com/45320291/132105480-1023c404-7802-430f-a4d6-fb7e723fc32a.png)

![image](https://user-images.githubusercontent.com/45320291/132105489-897ca833-1d02-4b27-93f7-36ba78adf24a.png)

**Comment by lorm6807** [comment]
Did you solve this problem?

**Comment by dmamel** [comment]
No

**Comment by lorm6807** [comment]
What's the Visual Studio version ?? I am Community 2019, because of the version?

**Comment by dmamel** [comment]
Community 2019 v16.11.2

**Comment by lorm6807** [comment]
You have updated it to the latest. I also like to... Thank you..ㅠㅠ

**Comment by beccamc** [comment]
The problem here is the Model Builder and GPU versions don't match. We released a new version of Model Builder (16.7.3) last week, but technical difficulties prevented us from releasing the GPU version. It's released now - please update here https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilderGPU

Sorry about this issue!

**Comment by dmamel** [comment]
When using the GPU, the accuracy of the model is <5%. If I train my dataset on CPU, the accuracy is 75%

**Comment by beccamc** [comment]
Any update here? @dmamel are you able to share your dataset?

**Comment by beccamc** [comment]
Original issue is resolved: MB version and GPU version need to match. @dmamel if you're still having accuracy issues can you open a new issue?
