### ISSUE TITLE
Loading a model trained on Model Builder is pretty slow.

### ISSUE THREAD

**Issue by Su-Bi-su** [dotnet/machinelearning-modelbuilder#1799]
**Is your feature request related to a problem? Please describe.**
Loading a model trained on Model Builder is pretty slow. This may not be an issue during object detection on a static image. However, it a quite a problem during real-time object detection.

**Describe the solution you'd like**
I would like the see that the model is loaded quickly so that there is no lagging during real-time object detection.

**Describe alternatives you've considered**
I am not able to find any alternative solution for this.

**Additional context**

**Comment by beccamc** [comment]
The initial load of the model can be slow, but subsequent uses should be faster due to caching. Are you reloading every time. @LittleLittleCloud Did you share some code samples for this recently?

**Comment by LittleLittleCloud** [comment]
@Su-Bi-su Can you describe your using case? Like How many pictures are you inferencing at one time and how much time does it cost for each image

**Comment by Su-Bi-su** [comment]
@beccamc yes the initial loading is slow and the subsequent uses are relatively fast. However, it is not as fast as I would expect it to be. 

@LittleLittleCloud : My use case is to detect object in a movable machine. 

I collected data, trained it using Model Builder and used this trained model for real time object detection. I am using USB camera for this purpose. The detection is good enough. However, when the machine is in motion the video capturing is quite slow. The video capturing itself is not slow, but it is slow when the trained model is used. 
I used the machine learning sample (https://github.com/dotnet/machinelearning-samples/tree/main/samples/csharp/end-to-end-apps/ObjectDetection-Onnx) as a reference. The sample project from the given link is quite fast while using the same USB camera. I know the program slows down when it is loading the model and getting the results. But I am not sure how can I fix this and make the program as fast as the sample project.

**Comment by luisquintanilla** [comment]
Hi @Su-Bi-su 

There's a few things at play here. The model used in the sample is small. I suspect with Model Builder, you trained using your own data. Therefore, the more data that you use, the larger your model becomes and as a result the higher the impact on latency. Since the object detection scenario is currently only available through Azure ML, other than training the model on your behalf, we don't have much control over the model training process. Some things you may want to try are using the ONNX Runtime tools available for tuning performance of these models. 

https://onnxruntime.ai/docs/performance/tune-performance.html#performance-tuning-tools

https://github.com/microsoft/OLive/tree/master/cmd-example#for-onnx-model-inference-optimization

Hope this helps. Closing this issue for now.
