### ISSUE TITLE
Change DLL Names and Namespaces

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#186]
**Bug description**
We need to update our assemblies to have better names.  Kathleen Dollard has sent out mail requiring all assemblies and tools to have Microsoft Prefix.

My Suggestion:

CLI: Microsoft.MachineLearning.Net.CLI
Model Builder: Microsoft.MachineLearning.Net.ModelBuilder
Code Gen: Microsoft.MachineLearning.Net.CodeGen

**Comment by JakeRadMSFT** [comment]
Goal is to increase confidence that something is coming from Microsoft (in addition to it being signed).

**Comment by justinormont** [comment]
I would sync w/ ML.NET folks on the topic of namespaces. I generally think these should be under Microsoft.ML.* namespace.

The `mlnet` NuGet was named to be able to have a short `dotnet tool install -g mlnet`.

/cc @eerhardt

**Comment by eerhardt** [comment]
> The mlnet NuGet was named to be able to have a short dotnet tool install -g mlnet.

Agreed. We should keep the CLI tool named `mlnet`. /cc @CESARDELATORRE @rustd 

>> Microsoft.MachineLearning.Net.CLI

> I generally think these should be under Microsoft.ML.* namespace.

I think we should keep `Microsoft.ML` instead of spelling out `MachineLearning` to match the runtime. Also `.Net.` in a .NET namespace or assembly name is redundant.

Maybe we could have all the tooling under `Microsoft.ML.Design.*`, or `Microsoft.ML.Tools.*`. Or possibly:


CLI: Microsoft.ML.CLI
Model Builder: Microsoft.ML.ModelBuilder
Code Gen: Microsoft.ML.CodeGen

**Comment by JakeRadMSFT** [comment]
I'm sold on the proposal from @eerhardt

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud lets update the names before adding the internals visible to :)

**Comment by LittleLittleCloud** [comment]
namespace for Code Gen will be: Microsft.ML.CodeGen

**Comment by JakeRadMSFT** [comment]
Please update to Microsft.ML.CodeGeneration

**Comment by LittleLittleCloud** [comment]
> Please update to Microsft.ML.CodeGeneration

Just the NameSpace? or also include the DLL

**Comment by JakeRadMSFT** [comment]
> > Please update to Microsft.ML.CodeGeneration
> 
> Just the NameSpace? or also include the DLL

Both
