### ISSUE TITLE
November CLI Release

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#1912]
Version number:
Build:
Commit:

- [ ]  Test Local Scenarios
- [ ]  Test Generated Code

**Comment by beccamc** [comment]
Important! Will be updating to .NET 6 for this release. Need to update docs. #1906

**Comment by LittleLittleCloud** [comment]
Due to the size limit on nuget, the cli will be splitted to three packages according to its RID, which will have the following pacakge ids

- microsoft.ml.modelbuilder.cli.win64
- microsoft.ml.modelbuilder.cli.osx
- microsoft.ml.modelbuilder.cli.linux64

Do we want to simplify the package name or just keep what we have.

**Comment by beccamc** [comment]
Per Jake, we need to speak with Bri regarding messaging for uninstall/install.

**Comment by LittleLittleCloud** [comment]
@beccamc @JakeRadMSFT @luisquintanilla 
After discussing, we decided to split mlnet.cli into three packages according to it's runtime and make it version matches with modelbuilders

- microsoft.ml.modelbuilder.cli.win64
- microsoft.ml.modelbuilder.cli.osx
- microsoft.ml.modelbuilder.cli.linux64

I'll update this thread once installment documents get changed

**Comment by LittleLittleCloud** [comment]
document updated
