### ISSUE TITLE
VS2022 always prompts to update package and then throws exception at the end of model training!

### ISSUE THREAD

**Issue by khteh** [dotnet/machinelearning-modelbuilder#1918]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.6.2152701
 - Visual Studio Version: 17.0.0
![image](https://user-images.githubusercontent.com/3871483/141884069-9973d6a9-0dca-45a4-ae5f-abaecd448497.png)
![image](https://user-images.githubusercontent.com/3871483/141884148-766caf50-0647-47a2-8479-8d074d620cbb.png)

[WebsiteSentiment-TSS0MD.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/7542856/WebsiteSentiment-TSS0MD.txt)

This happens even when there is no update shown in nuget package manager.
**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beccamc** [comment]
Thanks for reporting! Per the log file we're trying to update to 1.6.0

`Installing nuget package, package ID: Microsoft.ML, package Version: 1.6.0`

@khteh What type of project is this (.NET Core, framework...) and what version? Can you check the csproj?

**Comment by khteh** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="1.7.0" />
  </ItemGroup>
  <ItemGroup Label="WebsiteSentiment">
    <None Include="WebsiteSentiment.consumption.cs">
      <DependentUpon>WebsiteSentiment.mbconfig</DependentUpon>
    </None>
    <None Include="WebsiteSentiment.training.cs">
      <DependentUpon>WebsiteSentiment.mbconfig</DependentUpon>
    </None>
    <None Include="WebsiteSentiment.zip">
      <DependentUpon>WebsiteSentiment.mbconfig</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by beccamc** [comment]
Thank you @khteh! This helps a lot. 

The code checks to see if the current version and target version match, and if not it tries to upgrade. The problem here is that we're actually trying to downgrade from 1.7.0 to 1.6.0. @LittleLittleCloud Are we good to ignore the nuget package install if we'd actually be going backwards?

**Comment by LittleLittleCloud** [comment]
@khteh let us know if this error blocks you from model builder but you should be able to just ignore the error window since the downgrade error is a recoverable one.

@beccamc  We can ignore downgrade ml.net if there's no api breaking change for the newer version and the newer ml.net can always load old model. Otherwise it's better to try downgrading. However, I feel like it's always unsafe to try downgrading a package. Maybe a better way is just upgrade model builder which uses latest ml.net

The downgrading should be an uncommon case though since model builder should always stick to the latest ml.net. Since ml.net 1.7.0 is released, we should release a newer model builder asap.

**Comment by khteh** [comment]
Not a show-stopper but

> if there's no api breaking change for the newer version and the newer ml.net can always load old model
Can you verify this and provide a better VS2022 experience with ML.Net?

**Comment by LittleLittleCloud** [comment]
> Can you verify this and provide a better VS2022 experience with ML.Net?

Unfortunately under the current technology, there's no way to verify things that do not happen. even though mlnet will try their best to maintain backward compatibility. However we will push a fix and provides clearer information on such exception to avoid downgrading packages and  reduce confusions.

**Comment by beccamc** [comment]
This is completed and shipped! If you're still seeing a problem please open a new issue.
