### ISSUE TITLE
Ignore columns is creating a crazy ML model

### ISSUE THREAD

**Issue by dliedke** [dotnet/machinelearning-modelbuilder#1939]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  any version
 - Visual Studio Version 2019 or 2022

**Describe the bug**
The model is generated wrongly with incorrect Label when ignoring some columns from the table.

- Clear description of the problem:
**To Reproduce**

1) Train the ML model for multiclass text classification using a database table and ignore some columns.
2) The generated code will contain the ignored columns
3) The model generated will contain invalid labels

**Expected behavior**
Ignored columns should not be in the generated code (ex: ModelInput.cs) and should not be used for model training.

**Additional context**
Workaround: Create a view with only the columns required for the ML model. But this is a high severity issue.

**Comment by torronen** [comment]
Possibly related https://github.com/dotnet/machinelearning/issues/5919

**Comment by torronen** [comment]
I believe, most of the time at least, the ignored columns are ignored correctly. I tried reproduce in Model Builder with a file that had the label column copied as "ignore_this" colomn. "ignore_this" would reveal the result so trees should give perfect scores if not ignored. If there is a chance this might happen it may need to be tested with automated tools since manual reproducability seems difficult. 

Anyway, even if the ignored values would not be used for training, just having the ignored values in the model schema can cause minor issues. I have some old models but the ignored field is now dropped from the new dataset and live data. I still need to have a property for the dropped field to be able to consume the model. Worst case is 2+ models trained at different times; both have the ignored col but with different data types.

However, minor benefit from having the properties generated to ModelInput.cs is that I can use same class for all models, which may have different fields ignored (for comparison purposes, mostly)

**Comment by LittleLittleCloud** [comment]
Thanks for reporting, it's expected that the code will include ignored columns as ignoring column will only affect how training pipeline created, rather than how dataset get loaded. You can check on the generated training pipeline and you should find out that the ignored column is not used to train the model.

Can you give an example on invalid lable as well?

**Comment by dliedke** [comment]
Sorry, I can't provide the data I was using for training because it is company confidential. Thank you!

**Comment by torronen** [comment]
@LittleLittleCloud  
Some thoughts for consideration:
The columns are included in ModelInputSchema and ModelInput.cs. I have some few months old models, which include ignored columns in the schema. Ignored columns are removed from newer dataset files so I no longer have the data. This may be confusing (per original issue) but also cause minor issues in consuming the models:

`ITransformer model = mlContext.Model.Load(ModelZipPath, out DataViewSchema ModelInputSchema);`
 => ModelInputSchema includes ignored columns. In my case, secondary labels which are highly correlated with the primary label so they are not used to train the model - otherwise I should get near perfect scores.

This causes small issues: 
1. First, it tells me the fields are not included. 
2. Trying to manually add the columns, gives me errors like  `Column 'PredictedIsValid' is supposed to have item type System.ReadOnlyMemory`1[System.Char], but associated field has type System.Boolean (Parameter 'userSchemaDefinition')`.
3. Rare cases may have problems that the same columns has different types, even if it was ignored.

**Comment by torronen** [comment]
It seems the ignored columns have, in my case, Single or ReadOnlyMemory<char> for ignored Boolean fields. Reason might be that some were 1/0 and some were "true"/"false". 

It would be helpful if they were inferred with same way as non-ignored fields (original datatype boolean), or if they always had a specific data type (maybe object).
