### ISSUE TITLE
The ignore settings will not be reflected on Evaluate page and Code snippet of Consume page until reload the model builder. 

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1994]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.12.2.2207601
 - Microsoft Visual Studio Enterprise 2019: 16.11.9

**Describe the bug**
- On which step of the process did you run into an issue: Sample data on Evaluate page and Code snippet on Consume page.
- Clear description of the problem: 

1. Select Recommendation scenario, set one column to "ignore", complete the training, find that the ignore column displayed on Sample data on Evaluate page and Code snippet on Consume page;
2. Save the model and reopen it, the ignore column does not display.

**Expected behavior**
The ignore columns should not display on the Evaluate page and Code snippet of Consume page.

**Screenshots**
![ignore column issue3](https://user-images.githubusercontent.com/81727020/151517857-f94422d2-8856-46f8-9e61-30a04668fb73.gif)

**Comment by beccamc** [comment]
We had some other uses report problems with the ignore column. @vzhuqin can you confirm the ignore column is working right in the other scenarios. 

For recommendation, we should never show that timestamp column. Only the user/item is being used for training. This is a bug.

**Comment by vzhuqin** [comment]
@beccamc  Sorry, the description is not clear, this issue also occurs on other scenarios (Data classification, Recommendation).
Example (Data classification):
![image](https://user-images.githubusercontent.com/81727020/152715250-855c6214-9f47-4e60-9826-4c4541511afe.png)
![image](https://user-images.githubusercontent.com/81727020/152715268-507e31e1-28ea-48c6-8ef2-cca08bafaf80.png)

**Comment by luisquintanilla** [comment]
@v-Hailishi can you please validate whether this issue also affects the code that's generated in *.consumption.cs and *.training.cs files?

**Comment by v-Hailishi** [comment]
@luisquintanilla Using datafile [https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt](https://testpass.blob.core.windows.net/test-pass-data/issues.tsv.txt) as example.
I set column "ID" and "description" to Ignore, after completed training, I saw that *.training.cs file only contains feature column "Title", there is no column "ID" and "description". I think this issue doesn't affect the code that's generated in *.training.cs file.
But for *.consumption.cs file, I am not sure, because nothing is change whether I set column "ID" and "description" to Ignore or not.
![image](https://user-images.githubusercontent.com/99375895/162379193-7858ed38-79da-4c88-9f6e-92bb22164fc1.png)
![image](https://user-images.githubusercontent.com/99375895/162381039-14a7f3db-d4eb-43ff-b324-2938f486cba3.png)
[MLModel1.consumption.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/8449555/MLModel1.consumption.txt)

**Comment by v-Hailishi** [comment]
The bug has been fixed on the latest main build 16.14.0.2257101
![image](https://user-images.githubusercontent.com/99375895/203951694-b04af9c6-4ca1-4412-b192-a0c015fcc3b4.png)
