### ISSUE TITLE
Data preview does not update after set the column headers.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#2016]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.1.2210902 (latest main)
 - Microsoft Visual Studio Enterprise 2019: 16.11.10

**Describe the bug**
- On which step of the process did you run into an issue:  Data preview

- Clear description of the problem: after set the column headers, Data preview does not update. Please take a look if this is expected now?

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data classification and input data source;
5. Open Advanced data options dialog, set the headers to No, save the change;
6. See that Data preview does not update.

**Expected behavior**
Not sure if this is new expected behavior, please take a look?

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/153325163-7c68232e-87d8-4c49-990a-ecab968fad5a.png)

**Comment by beccamc** [comment]
@v-Hailishi I thought this was working a few days ago. Would you mind trying this again?

**Comment by v-Hailishi** [comment]
@beccamc Verified on the latest build version 16.13.5.2212401, this issue is still present.
After changing the button from "Yes" to "No", the column header is still appeared in the Data preview table.

Besides, the total rows are changed from "249" to "250", which I think strange, shouldn't the number of rows stay the same?
Could you help to give the correct behavior here?
![image](https://user-images.githubusercontent.com/99375895/156094177-45ddf2c5-a986-474f-b612-cb7e02b3e904.png)

**Comment by beccamc** [comment]
Thank you for checking this! The reason the row number changes is because what we previously counted as "header" is now a row. Headers aren't counted in the row count.

**Comment by v-Hailishi** [comment]
@beccamc According to your explaining, below behaviors are expected, right? 
1. After changing the button from "Yes" to "No", the Data preview table keep the same.
2. After changing the button from "Yes" to "No", the total rows are changed from "249" to "250".

**Comment by beccamc** [comment]
This behavior is expected. Closing
