### ISSUE TITLE
Get "Input string was not in the correct format" error for Azure image classification when Azure's regieon format is Poland

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning-modelbuilder#2035]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.13.2
 - Visual Studio Version

To reproduce
- set system region format to russia/Poland (whatever decimal separator is ',')
- run azure image classification

**Comment by v-Hailishi** [comment]
The bug is not repro on the latest main branch: 16.13.5.2216501.
After change the system region format to Russia/Poland like below, the Azure image classification can success to train, evaluate, consume and run the generated projects. There is no error in whole progress.
![image.png](https://images.zenhubusercontent.com/62158d7f86929a769f3d134a/aaf24b11-21db-4739-a121-6dde3f5b65f4)
