### ISSUE TITLE
Sample Project generated by CLI does not launch in Visual Studio 2022

### ISSUE THREAD

**Issue by arafattehsin** [dotnet/machinelearning-modelbuilder#2148]
**System Information (please complete the following information):**
 - OS & Version: Windows 11 
 - ML.NET Version:  ML.NET CLI version 16.3.6
 - .NET Version: 6.0

**Describe the bug**
When I try to create a sample project using ML.NET CLI, I get an error message in launching the library / application.

**To Reproduce**
1. Create a classification model using ML.NET CLI
2. Try to open up the Sample Project generated
3. See an error on Visual Studio 2022 17.3.0 Preview 1.1
![image](https://user-images.githubusercontent.com/16351038/172600372-71bf3245-0a04-4ee1-b462-ad1b020c9c71.png)

**Expected behavior**
It should open up the file without any issues

**Comment by beccamc** [comment]
@v-Hailishi Can you try to reproduce this?

**Comment by v-Hailishi** [comment]
@beccamc The bug is not repro on the latest MLNET CLI version **16.13.8**.

The following are my repro steps:
1. Install install MLNET CLI by run command: 
    **dotnet tool install -g mlnet-win-x64 --add-source https://mlnetcli.blob.core.windows.net/mlnetcli/index.json**
    <img width="422" alt="image" src="https://user-images.githubusercontent.com/99375895/173529208-1b65ca5c-2032-4536-9c0b-343137c8f75f.png">
2. Run the following ML.NET CLI command to generate a sample project.
    **mlnet classification --dataset "yelp_labelled.txt" --label-col 1 --has-header false --train-time 10**
   <img width="425" alt="image" src="https://user-images.githubusercontent.com/99375895/173530011-63e05084-50df-47df-a345-3be22157b2ed.png">
3. I can open the sample project successfully.
    <img width="704" alt="image" src="https://user-images.githubusercontent.com/99375895/173532395-25c58e5f-1aa7-4edc-863e-c29ed4fe6a75.png">

**Comment by arafattehsin** [comment]
Hey team. The latest version does not have this issue so I am happy to close it. I think dotnet CLI is still installing the older version which is 16.13.6

**Comment by beccamc** [comment]
@luisquintanilla Can you look at the dotnet CLI installing the older version? Is that something you can look at?

**Comment by luisquintanilla** [comment]
Just did a fresh install from Windows using Docs and the right version installed. I think we can close this issue. However to avoid confusion we might want to deprecate or unlist the mlnet global tool in NuGet because it still shows up. 

https://docs.microsoft.com/dotnet/machine-learning/how-to-guides/install-ml-net-cli?tabs=windows

![image](https://user-images.githubusercontent.com/46974588/174169279-e21dc430-69dc-44a3-8683-6e222fbe6b7c.png)
