### ISSUE TITLE
Error in Running ML.NET Model(https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/intro)

### ISSUE THREAD

**Issue by spramanik96** [dotnet/machinelearning-modelbuilder#2165]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable): VS 2022 Community

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): last Page
- Clear description of the problem: Following Error Message when myMLApp is run

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your pro
![Capture](https://user-images.githubusercontent.com/107580026/173929953-d6436775-c570-4bc2-a1e7-f3acd315c5f3.PNG)
blem.

**Additional context**
![Capture](https://user-images.githubusercontent.com/107580026/173930126-36f1f987-0d2e-4d66-a95b-4730163f28de.PNG)

**Comment by beccamc** [comment]
Sorry you ran into this problem! I think you're on an older version of Model Builder that uses "Prediction" instead of "PredicatedLabel". You can update from the [Marketplace](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022). 

This is a duplicate of https://github.com/dotnet/machinelearning-modelbuilder/issues/2128.

**Comment by beccamc** [comment]
Please see the [troubleshooting](https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md) doc for more info on this problem.
