### ISSUE TITLE
model builder nuget source included in Nuget.config

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#217]
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
I cloned the repo and wasn't able to build due to a problem with the model builder package sourced from https://www.myget.org/F/model-builder/auth/60400d4f-8127-4d35-84eb-11bc2b5337a9/api/v3/index.json.  

**To Reproduce**
Try to update model builder package. 

**Expected behavior**
Question: Is this package necessary? 

**Screenshots**
![image](https://user-images.githubusercontent.com/9122518/63134394-30fa3800-bf7e-11e9-9085-bc8452504d57.png)

**Additional context**
Jake took a look, and it seems to be added by @LittleLittleCloud. Can this be removed Xiaoyun? :)

**Comment by LittleLittleCloud** [comment]
The error is caused due to the expiration of MyGet subscription. We don't need MyGet currently, so just remove that item from Nuget.config will solve this problem.

In the meantime, after we use ServiceHub to host AutoMLEngine service, we might still need a place to provide private feed. Maybe we can consider using vsts?
