### ISSUE TITLE
ML.NET Tutorial - Get started in 10 minutes is not running

### ISSUE THREAD

**Issue by victorarshon** [dotnet/machinelearning-modelbuilder#2180]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (2022):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/consume
- Clear description of the problem: I have replaced the code in the Program.cs as it is recommended. But when I tried  (Ctrl+F5) to run the program I received the error CS1061. Please see the images attached.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8861560/176314633-f3521ab2-9d3b-4abf-9b88-627f8704c6f9.png)
![image](https://user-images.githubusercontent.com/8861560/176315138-2e3521cd-38bc-4a18-a689-3bc6fe926be9.png)

**Additional context**

**Comment by beccamc** [comment]
Sorry for the confusion here! This happens when you run the tutorial on an older version of Model Builder, which generates code referencing an older version of ML.NET. 

In a newer version of ML.NET the property `Prediction `was renamed to `PredictedLabel`. There are a few options for resolving this.

- Change PredictedLabel to Prediction.
- Update ML.NET to 1.7.1
- Update Model Builder version to the [latest](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022) and re-train the model

**Comment by PurdueSimon** [comment]
might need to downgrade to VS2019 as i did to get things running...

**Comment by beccamc** [comment]
If anyone else runs into this, please update Model Builder to the latest version and re-train the model. 

Or change "PredictedLabel" to "Prediction". [Troubleshooting](https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#cannot-run-code-from-tutorial-because-predictedlabel-does-not-exist) for more information.
