### ISSUE TITLE
Tied accuracy lists the second as Best Algorithm

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#221]
**System Information (please complete the following information):**
 - Model Builder Version: master

**Describe the bug**
There is a tie between the accuracy of two algorithms. One is listed as 1, and has higher AUC. However, 2 is shown as "Best algorithm"

**To Reproduce**
1. Not sure how, but get the same accuracy for two algorithms.

**Expected behavior**
The first algorithm listed is the best 

**Screenshots**
![image](https://user-images.githubusercontent.com/9122518/64299338-c2c9e500-cf2d-11e9-8b4b-f60ebc79961e.png)

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud lets at least root cause this. I'd like to know if it's our bug or AutoML.

@beccamc which scenario, dataset, and training time did you use?

**Comment by justinormont** [comment]
@beccamc: for at least display purposes, it seems we're incorrectly displaying the wrong model. I think this is occurring in ModelBuilder (vs. the CLI or AutoML) as the CLI below is displaying the order I would expect. I believe the tie breaker is current the iteration number. In the future, we could implement a better tie breaker on secondary metrics like AUC.

Can you look at the generated code? Did the generated code use `FastTreeBinary` or `AveragedPerceptronBinary`? This should be telling of where the issue lies.

Side note: 
As @JakeRadMSFT mentions, you'll likely want a longer runtime. Perhaps use ~20 min for your dataset. The largest iteration I see in your list is iteration `#6` with a total of ~60 sec. You'll generally want to aim at a time which finishes 80-200 iterations.

**Comment by vzhuqin** [comment]
@beccamc could you help to provide the dataset and train time you use to validate this issue?

**Comment by beccamc** [comment]
This is very old, and no customers have reported this. I'm going to close this as low priority.
