### ISSUE TITLE
The program.cs code seems incomplete.  I replaced the program.cs code with the code provided and it will not compile.

### ISSUE THREAD

**Issue by CBelmonte** [dotnet/machinelearning-modelbuilder#2231]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by luisquintanilla** [comment]
Hi @CBelmonte can you please provide more details on the issue you're seeing

**Comment by beccamc** [comment]
@CBelmonte Is this the problem you're seeing? https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#cannot-run-code-from-tutorial-because-predictedlabel-does-not-exist

**Comment by beccamc** [comment]
We don't have enough information to investigate this issue. If your issue is not the same as [this](https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#cannot-run-code-from-tutorial-because-predictedlabel-does-not-exist) feel free to open a new bug.
