### ISSUE TITLE
Add DirectML support

### ISSUE THREAD

**Issue by Gsonovb** [dotnet/machinelearning-modelbuilder#2262]
Hi,

I would like ModelBuilder to support DirectML so that it can be compatible with more Gpus.

**Comment by luisquintanilla** [comment]
Hi @Gsonovb 

Thanks for this issue. Since DirectML support is not currently available in the ML.NET framework, it's not possible at this time to enable it in Model Builder / ML.NET CLI. 
There is an issue in the dotnet/machinelearning repo. Please use that issue to track any developments there. 

dotnet/machinelearning#5240

Closing this issue for now and if/when ML.NET offers DirectML support, we'll work to enable it in the tools.
