### ISSUE TITLE
Forecasting: The column name is incorrect in the Output window when using metric "MAPE".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2315]
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-21H2
ML.Net Model Builder 2022: 16.14.0.2252402 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.3.6)
.Net: 6.0

**Describe the bug**
- On which step of the process did you run into an issue: 
The column name is incorrect in the Output window when using metric "MAPE".

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/forecasting.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core6.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Forecasting** scenario.
  5. On Data page, select the data source and choose "**sinx**" column as label.
  6. On the Train page, click "Advanced training options..." link, then choose metric "MAPE" and save it.
  7. Click "Start training" button to complete the training and then check the column name in the Output window.

**Expected behavior**
The column name should be displayed correctly.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/197736322-16e61de1-26a4-4f2b-93bf-0259d2625283.png)

**Comment by zewditu** [comment]
We have a bug for the metric MAPE because it is not implemented in AuoMl as `RegressionMetric`. Even if the user Selects MAPE from model builder but in automl experiment we passed RMSE that is why the output window shows that because it is from Automl service

Suggestion: Implement it in AutoML or turn off this metric from forecasting scenario.
@LittleLittleCloud  any thought?
