### ISSUE TITLE
System.NotImplementedException when attempting mlnet tutorial. mlnet installed.

### ISSUE THREAD

**Issue by aarianmm** [dotnet/machinelearning-modelbuilder#2408]
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 
 - Visual Studio Version (if applicable):

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/114620482/206569743-73a43150-fb3e-4cde-becb-6c868efbfa03.png">

**Comment by 3zero2** [comment]
I'm running into the same issue. Filling in the form properly:

**System Information (please complete the following information):**

- Model Builder or CLI Version: 16.14.0
- Visual Studio Version (if applicable): NA

**Describe the bug**

- On which page of the tutorial did you run into an issue (URL):  https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/train
- Clear description of the problem: Upon running the `mlnet classification --dataset "yelp_labelled.txt" --label-col 1 --has-header false --name SentimentModel  --train-time 60` command a System.NotImplementedException occurs. 
- 

To Reproduce
Steps to reproduce the behavior:

1. Create folder
2. Download dataset into folder
3. Run `mlnet classification --dataset "yelp_labelled.txt" --label-col 1 --has-header false --name SentimentModel  --train-time 60`
4. Error message appears as per post above.

**Expected behavior**
Training completes and summary should be presented.

**Screenshots**
Screenshot posted above.

Additional context
Add any other context about the problem here.

**Comment by 3zero2** [comment]
How did you train on dotnet7? 

I installed dotNet6 just to be able to follow this tutorial as with only dotnet7 installed it was complaining of not finding dotnet6.

Are you running on Ventura?

**Comment by aarianmm** [comment]
I already had dotnet 7 installed and mlnet seemed to behave fine until i tried to train the model. i used a global.json file to use dotnet 6 as well as that’s what the tutorial used, and it still did not work. i also uninstalled and reinstalled mlnet a few times and the issue didn’t resolve.

**Comment by gbanuk2** [comment]
This sounds like the same issue as bug 2406. I have reverted to the previous version of mlnet so I can continue to work until it's fixed.
dotnet tool install --global mlnet-win-x64 --version 16.13.9

**Comment by 3zero2** [comment]
You're right @gbanuk2. This is the same issue as #2406. Reverting to version 16.13.9 did the trick.

So for anyone reading it's:

1. First uninstall current version of mlnet with `dotnet tool uninstall mlnet-osx-arm64 -g`
2. Install previous version with: `dotnet tool install -g mlnet-osx-arm64 --version 16.13.9`

**Comment by xumix** [comment]
The bug still occurs in 16.15.1

**Comment by xumix** [comment]
The bug still occurs in 16.15.1 @beccamc
