### ISSUE TITLE
*.MLNET change issues with old mbconfig files

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#2439]
- [ ] Evaluate page doesn't work until retrained or until zip is renamed to mlnet
<img width="479" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/31937616/211921092-2dedad60-0a04-417f-aa84-f7de5cf5e7b1.png">

- [ ] Old zip doesn't get cleaned up on retraining

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/31937616/211921115-b506a6a2-03fa-4642-8827-33b0b76f5489.png)

- [ ] Sample project generation using old mbconfig file(model.zip) failed

Suggested fix: detect if there is a zip file and rename.

**Comment by LittleLittleCloud** [comment]
renaming file from .zip to .mlnet is a break change. It will prevent old model builder from loading existing .mbconfig once we update model name.

I feel like a safer way to fix this issue is by introducing a new field in `ITrainResult` calls `ModelPath` and pointing it to the existing model.  The old .mbconfig can be safely migrated to the new schema by filling `ModelPath` with trained model. And for new .mbconfig the model can be saved with `.mlnet` extension.

**Comment by beccamc** [comment]
Validated by Jake

![Image](https://user-images.githubusercontent.com/9122518/214155714-3cf70105-bb8a-450d-b5c0-33aac90261da.png)
