### ISSUE TITLE
Single float column being set to string

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#2478]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version: VS2022

**Describe the bug**
- On which step of the process did you run into an issue: Data
- Clear description of the problem: Relevance column is a float, but it's being set to "String".

**Expected behavior**

Relevance should be recognized as a float

**Screenshots**

![image](https://user-images.githubusercontent.com/46974588/217293676-4007a55b-c7aa-4a93-a4e0-c417860c039b.png)

![image](https://user-images.githubusercontent.com/46974588/217293526-029af8f6-412a-4ed6-ac77-ef856d5bf07d.png)

**Dataset**

https://www.kaggle.com/competitions/home-depot-product-search-relevance/data?select=train.csv.zip

**Comment by zewditu** [comment]
@beccamc  is this related to pros file  scanning ?

**Comment by luisquintanilla** [comment]
Related to #1442

**Comment by beccamc** [comment]
This is not a PROSE issue. The problem is with commas in the dataset. Specifically these lines... 

```
117,100022,"Samsung 4.2 cu. ft. Front Load Washer with Steam in White, ENERGY STAR","PLATFORM FOR WASHERS",2.67
120,100022,"Samsung 4.2 cu. ft. Front Load Washer with Steam in White, ENERGY STAR","samsung front load washer 3.7",2
122,100022,"Samsung 4.2 cu. ft. Front Load Washer with Steam in White, ENERGY STAR","upholstery washing machines with steam",2.33
```

[GetRichDataTypes](https://github.com/dotnet/machinelearning-tools/blob/065eccb0999574597a20f4fa567fedaad83bb835/src/Microsoft.ML.ModelBuilder.AutoMLService/DataProcessingEngine.cs#L49) is splitting on the "," character and not respecting the quotation marks. This is what we are passing to PROSE for these data rows. It thinks relevance is a string because we are including string information. 

id | product_uid | product_title | search_term | relevance |  extra column|
|---|---|---|---|---|---|
|  117 | 100022  |  Samsung 4.2 cu. ft. Front Load Washer with Steam in White | ENERGY STAR  | PLATFORM FOR WASHERS  | 2.67|

**Comment by luisquintanilla** [comment]
Closing this issue since the error was on the dataset.

**Comment by luisquintanilla** [comment]
> @luisquintanilla This isn't a problem in the dataset. The dataset is correctly using commas. We are splitting the dataset incorrectly by using string.split(","). This doesn't respect the quotation marks. This probably needs to be solved using regex.

Thanks for that clarification. I'll reopen the issue.
