### ISSUE TITLE
Move to larger dataset in the getting started guide

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-modelbuilder#323]
We should increase the size of the dataset sample used in the [getting started guide](https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train). 

The 250-line sampled dataset is currently sized for a unit test; its small size is not valuable for example code, where a useful model is needed. Perhaps we should increase the size of the sample for use in the example. If the same dataset is used in unit tests, we should ensure the runtime of the unit tests are not adversely impacted. The only point of the unit tests are to see if _something_ changed; they are _not_ expected to make useful models. 

Similar issues were mentioned in the main repo: https://github.com/dotnet/machinelearning/issues/708#issuecomment-425706329:
> Try running on the full-sized dataset: https://aka.ms/tlc-resources/benchmarks/WikiDetoxAnnotated160kRows.tsv
>
> The `wikipedia-detox-250-line-data.tsv` dataset is a 250 row sample of the original 160k rows. Training on this small of a sample won't create a useful model.

_Originally posted by @justinormont in https://github.com/dotnet/machinelearning-modelbuilder/issues/308#issuecomment-550545373_

**Comment by briacht** [comment]
@justinormont I agree about using a different/better dataset. Unfortunately the full-sized dataset takes a little too long to train for a getting started tutorial (~30 seconds should be the MAX, but Model Builder suggests 600 seconds for this dataset -- I was able to get 1 model explored in 80 seconds).

I really wanted to use the yelp-labelled dataset from: https://archive.ics.uci.edu/ml/datasets/Sentiment+Labelled+Sentences
because it gives great results with even just 10 seconds of Train time (it's what I use in demos), but there is no header which means it won't work in Model Builder. We can't modify the dataset to add a header and host it because of copyright issues, and instructing people to open their dataset and add a header in the tutorial interrupts the flow of using Model Builder.

Do you know of any other sentiment datasets that are larger than the 250-line sample but smaller than the full sample?

**Comment by justinormont** [comment]
Try a larger sample of WikiDetox. The current 250 rows is way too small, but for a sample, we also don't need the full size (160k rows).

To find a good sample size, you can create the [learning curves](https://en.wikipedia.org/wiki/Learning_curve_(machine_learning)) by altering the number of rows in the sample and tracking the accuracy. For the sample, look for when the curve no longer looks noisy (as opposed to peaking out the accuracy); this will cause the sample to generally give users the same answer each time. Then we have to ensure the runtime is acceptable at the number of rows. Without testing, I'd recommend a sample around 20k rows.

Also, we want to be realistic with our users. We shouldn't give them the impression that 30s is a normal runtime.

**Comment by briacht** [comment]
We now use the yelp labelled dataset which contains more rows and gives a better model.
