### ISSUE TITLE
Negative RSquared

### ISSUE THREAD

**Issue by brunoperret** [dotnet/machinelearning-modelbuilder#333]
**Model Builder Version 1.3.1: _In which Model Builder version was the bug encountered?_
**Visual Studio Version 2019: _In which Visual Studio version was the bug encountered?_

**Bug description**
Not sure it is a bug. Sometimes I have RSquared < 0 when training regression model.

**Steps to Reproduce**
1. I choose Price Prediction scenario, I select a TSV file with 8 columns, attach here in ZIP format
[testGC4.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/3823678/testGC4.zip)
I select column 8 (PC1) to be predicted from the 7 first columns.

**Expected Experience**
A sceenshot of the resulting RSquared
![NegativeRSquared](https://user-images.githubusercontent.com/47967375/68462483-eac71480-020c-11ea-9453-03000c4f1185.png)
Thanks !

**Comment by justinormont** [comment]
The negative R2 values indicates a useful model couldn't be found:
https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/metrics#metrics-for-regression

Often the negative R2  indicates distributional shift between your training and validation datasets. Since Model Builder is using a train/validate or CV on a single dataset, this indicate the need of more data, since it comes from a single dataset only randomness of the splits remain. With more data, even with nothing informative in your features to help it guess your label, the models should hit `0.0` in CV or TrainValidate modes. 

Possible work to assist users:
* Print (approximate) number of rows in the GUI -- sample the first 1k estimate total rows (recommend calling [AutoML's function](https://github.com/dotnet/machinelearning/blob/e50c4d20012e0d62852f404ae443afca7dad043e/src/Microsoft.ML.AutoML/ColumnInference/TextFileSample.cs#L74-L80) for this which returns a TextFileSample which has an _approximateRowCount field)
* Calculate error bars from CV, print warning in GUI saying more data is needed if >10 models are trained and the 0.95CI error bars for the best model are wider than 10%. After the approx row count: "More data may be needed".
* _(side item)_ If < 100 models are trained, add a warning that more time may be needed, and suggest `time=150*(timeTaken/numModelsExplored)`, which aims at 150 models. This can be calculated during the training process as an earlier warning.

**Comment by brunoperret** [comment]
Thanks a lot for your answer. This will be very helpful for me
Bruno
