### ISSUE TITLE
Labeling for "Sentiment"?

### ISSUE THREAD

**Issue by saheel-ahmed** [dotnet/machinelearning-modelbuilder#336]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I didn't understand why we need to Label?

I was checking the demo with H2o.ai

There is no such "Sentiment" as a label have to set like this, it is simply a predict data column alone.

Please help me to understand why we need for the Model.

**Comment by briacht** [comment]
Hey @saheel-ahmed ,

In machine learning, the columns that are used to make a prediction (inputs) are called **Features**, and the column that you'd like to predict is called the **Label**.

So for the sentiment analysis example in the tutorial, you want to predict sentiment based on just the comments left by users:

![image](https://user-images.githubusercontent.com/10437687/68964979-b45b3d80-07a8-11ea-8945-dc31969664c3.png)
 
The column with the user comment text (_SentimentText_) is the Feature column. The column with the sentiments (1/0 or negative/positive) of the comments (_Sentiment_) is the Label column, since you want to predict the sentiment.

You can learn more about machine learning / ML.NET basics [here](https://www.youtube.com/playlist?list=PLdo4fOcmZ0oUDTvk5XMNues09FnuB_D0u).

Does that help?

**Comment by saheel-ahmed** [comment]
Thank you, Bri Achtman, for your email.

I was comparing this with Python AI tools

There they don't need any label column just the text and in Model, it is
returning the result. So I'm confused why we are using in the ML.net

I checked in H2o.ai there also no label as column.

**Comment by briacht** [comment]
In H2O.ai, the "target column" is the same as Model Builder's "Label" column.

So whichever column is the information you want to predict in your dataset (in the case of sentiment analysis, you want to predict the Sentiment; in the case of taxi fare price prediction, you want to predict the Price of the fare amount) is the target or label column.

In H2O.ai documentation, there is an example for sentiment analysis: http://docs.h2o.ai/driverless-ai/latest-stable/docs/userguide/nlp.html#a-typical-nlp-example-sentiment-analysis

The dataset they use has two columns, text and airline_sentiment, and these are the instructions:
"Once we have our dataset ready in the tabular format, we are all set to use the Driverless AI. Similar to other problems in the Driverless AI setup, we need to choose the dataset, and then **specify the target column** (‘airline_sentiment’)."

Does that help answer your question?

**Comment by beccamc** [comment]
@saheel-ahmed Did Bri answer your question?

**Comment by beccamc** [comment]
@saheel-ahmed Thanks for reporting! We're closing this issue. If you're still experiencing a problem please comment or reopen.
