### ISSUE TITLE
model builder hit an unexpected error unrecognized data ml.net

### ISSUE THREAD

**Issue by dotnettrainingacademy** [dotnet/machinelearning-modelbuilder#356]
![657](https://user-images.githubusercontent.com/50792322/69016735-36c14880-09c7-11ea-8394-39b6b8b8e5c0.PNG)

**When i upload this csv [data ](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge)for model training it is throwing error in visual studio 2019**

**Comment by JakeRadMSFT** [comment]
Can you please provide more information? What issue did you hit? Can you please share the "Machine Learning" Output logs.

**Comment by dotnettrainingacademy** [comment]
> Can you please provide more information? What issue did you hit? Can you please share the "Machine Learning" Output logs.

When i upload this csv [data ](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge)for model training it is throwing error

**Comment by JakeRadMSFT** [comment]
Thanks for providing the dataset! We'll look into it!

**Comment by LittleLittleCloud** [comment]
dup of #327

**Comment by behroozbc** [comment]
hi i have same problem with 
this data is from kaggle data
[titanic.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/4061311/titanic.zip)

**Comment by beccamc** [comment]
Prose flat file parsing fixes the unrecognized data error for the jigsaw dataset. I'm still getting an error from inferColumns() so more works needs to be done here. 

Titantic dataset works with the 16.6 preview release.

**Comment by beccamc** [comment]
@dotnettrainingacademy There are two problems here for the jigsaw dataset... 
1. Model Builder fails parsing the dataset -> This will be fixed in our next version release
2. ML.NET has problems with the newlines in the comment_text field. I took a subset of the data and removed the newlines and it worked. -> We're working with partner teams on fixing this.

To avoid both bugs you could update to the newest version of Model Builder (available in VS 16.6 Preview 2) and and remove all the newlines from the dataset. I know this workaround is far from ideal... we're working on fixing this and getting to you. 

@behroozbc Titanic dataset will work now on the newest version of Model Builder (available in VS 2019 preview build)

Thanks for reporting!

**Comment by IvalinV** [comment]
Hi, all

I have similar problem to @dotnettrainingacademy
Using VS 16.6.3

![image](https://user-images.githubusercontent.com/20267863/86533138-92e5c800-bed7-11ea-8bfb-f6cf254ca6df.png)

That's the data set i'm using it is .txt file

**Comment by beccamc** [comment]
@IvalinV In the newest version of Model Builder this should be fixed. I might also try enclosing the coordinates in quotes so the parser knows it is one field -> "x 195 12344 y 195 123444"

**Comment by IvalinV** [comment]
Thank you, @beccamc I will try it right way

**Comment by LittleLittleCloud** [comment]
try this [data](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge) and it LGTM
