### ISSUE TITLE
Issues classification not working

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#377]
Using the github data set [here](https://app.zenhub.com/files/186917455/2e43579d-0d8d-4e26-920c-14b5a1aea9db/download).  This is the first training I'm doing (not running another scenario and then this scenario)

Its finalizing forever, and never prints anything to console. 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/748859ee-845a-4d21-a0f4-67b382988acd)

**Comment by Technocrux** [comment]
Same here, not working. Not able to train through model builder

**Comment by LittleLittleCloud** [comment]
Some bugs that might relate to this one
#365

**Comment by zewditu** [comment]
I am not able to validate this  issue with [this](https://app.zenhub.com/files/186917455/2e43579d-0d8d-4e26-920c-14b5a1aea9db/download )  data-set  because the following error dialog is is popup before the training time finished.
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/49dfafd8-1edd-47e2-8cde-fd9d9e292231)

**Comment by JakeRadMSFT** [comment]
Seems broken still

**Comment by JakeRadMSFT** [comment]
Just needs more training time.
