### ISSUE TITLE
Model builder improvements , Image classification scenario .

### ISSUE THREAD

**Issue by mauryflag** [dotnet/machinelearning-modelbuilder#418]
Great job guys !!! some suggestions ...

Add the chance to do all model builder steps , including code generation , by using GPU.
Add the chance to made  multiple test classification ( as example by  loading images from a folder).
Add the chance to made test classification by loading an existing model.
Add the chance to load images from SQL database from varbinary field.

**Comment by LittleLittleCloud** [comment]
Thank you for your feedback, Great suggestions! We will take it into consideration.

**Comment by beccamc** [comment]
@JakeRadMSFT To break up this issue into correct epics.

**Comment by JakeRadMSFT** [comment]
@mauryflag - I'm splitting up this issue so that we can triage/prioritize each suggestion separately.

"Add the chance to do all model builder steps , including code generation , by using GPU." 

For this do you mean having the generated code use GPU (like just update the NuGet reference to be the GPU tensorflow)?


Add the chance to made multiple test classification. Semi related - #60 #1588

**Comment by JakeRadMSFT** [comment]
"Add the chance to made multiple test classification." Semi related - #60 #1588

**Comment by JakeRadMSFT** [comment]
"Add the chance to made test classification by loading an existing model"

@mauryflag Can you expand on this one a bit? We added the ability to save and re-open mbconfig ... does that work for this?

**Comment by beccamc** [comment]
Thanks for the suggestions! These are being tracked in the linked issues. Thanks!
