### ISSUE TITLE
CSV or TSV Dataset with double quotes doesn't work

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [dotnet/machinelearning-modelbuilder#452]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1911.1103
 - Visual Studio Version: 16.4.3

**Describe the bug**
[Titanic dataset](https://www.kaggle.com/c/titanic/data) from kaggle.com

I can't process this data set, because data on the Name column between double quotes.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/29052211/72802992-3c0a7000-3c62-11ea-87e1-b76a3d40c780.png)

**Comment by LittleLittleCloud** [comment]
Thanks for your feedback
dup of #327

**Comment by beccamc** [comment]
@Cyrus-Sushiant Thanks for reporting. We're actively working on improving our data input experience, and this bug is known (see Xiaoyun's link above). I don't yet have an ETA on a fix. To get easily unblocked you could reformat your data to "First Last Name" via excel's [Flash Fill](https://support.office.com/en-us/article/using-flash-fill-in-excel-3f9bcf1e-db93-4890-94a0-1578341f73f7) feature. 

Sorry for the inconvenience!

**Comment by LittleLittleCloud** [comment]
dup of #435
