### ISSUE TITLE
Azure training - thinks train time is 0

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#504]
When I hit train after setting up Azure settings:
![image](https://user-images.githubusercontent.com/10437687/74191366-4f2cb200-4c08-11ea-83ef-72e616d34400.png)

When I hit Yes:
![image](https://user-images.githubusercontent.com/10437687/74191445-6d92ad80-4c08-11ea-85b9-6ec262b9ee8e.png)

**Comment by zewditu** [comment]
I think this one was because of someone set training parameter's training time for image  to zero because input  training time does not have any effect  , currently it stetted to maximum value  about 24 hours  but for some reason that I am not sure why  is raised exception when we set it to zero. now it is already back to the original one 24 hours ,
