### ISSUE TITLE
Improve Experience for data file is open in other program.

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#530]
Update: We can fix this by correctly specifying the FileShare parameter in the FileStream. Users can have their files open in Notepad and other programs, so why not excel? Trying approach to fix the problem before implementing the retry experience Jake suggested below.

---------------------------------------------------
Today we throw an exception that is pretty clear. I think we should come up with a better experience though ... with a custom dialog.

Something like:
"The selected dataset is open in another program. Please close other programs and retry or choose another dataset."

[ Retry ] [ Cancel ]

**Comment by JakeRadMSFT** [comment]
It currently gets stuck "Downloading" in Training if the files is opened after Data Screen but before Start Training.

**Comment by beccamc** [comment]
I've fixed the problem from the Model builder side, but we're still seeing errors from AutoML

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/23e875f9-24ad-411f-90cb-77bd73a75395)

**Comment by beccamc** [comment]
AutoML has concerns about allowing file writes while reading. See more details in [this ](https://github.com/dotnet/machinelearning/pull/5128)PR discussion. Returning to Retry pattern suggested by Jake

**Comment by beccamc** [comment]
1. This experience is **fixed** for the data page. You don't have to re-open the file explorer anymore
2. This experience is broken for training. ML.Net doesn't want to fix. I see only marginal benefit from adding a "Retry" button here because the action the user must take to retry is already a single button press. I see the error message, close the file, hit "Train again" 

![BlockedProcess.gif](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/a34a0eff-13ec-40b8-ad5b-207f1eff05af)

I'm proposing adding a retry at this time isn't useful, but we could improve the error message.
