### ISSUE TITLE
[Azure] - 400 Error on Create Compute dialog

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning-modelbuilder#540]
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.2002.2301
 - Visual Studio Version: VS2017 & VS2019

**Describe the bug**

When creating a compute, a 400 Bad Request error dialog appears regardless of which compute type is selected.

**Screenshots**

![image](https://user-images.githubusercontent.com/46974588/75199978-80da6880-5732-11ea-9ac6-397eaaae49d4.png)

**Comment by beccamc** [comment]
A few things here...

1. Root cause of this was a duplicate name for computes.  This error occurred before we further limited the GPU sizes. To repro, select a NV size, get a quota error, and try again with the same name. Server returns a 400 because it already has a (failed) compute by that name. This is now mitigated because no quota computes are available. 
2. We're showing a better error message now that includes the 400 details. For example... 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/195416e7-27af-4d5c-978a-80d1a28ea4c0)

Fixed.
