### ISSUE TITLE
Azure training failed

### ISSUE THREAD

**Issue by natke** [dotnet/machinelearning-modelbuilder#544]
**Model Builder Version**: _16.0.2002.2301_
**Visual Studion Version**: Microsoft Visual Studio Enterprise 2019, Version 16.4.3

**Bug description**
_Azure training failed._

**Steps to Reproduce**
1. Run the Model Builder Image Classification Azure training experience
2. Training fails

**Additional Context**

![ModelBuilderExFail.PNG](https://images.zenhubusercontent.com/5ce48d4d5eba81334339009f/ba82a570-81d0-4961-b77d-1c767c2cfaee)

**Comment by beccamc** [comment]
Hmmm... I'm not sure what happened here. On the model builder side we've added retries and have work items for the most common problems users run into. 

Moving forward we need a way to report these Azure specific problems to the Azure team (since external customers won't be able to give us a link to their run). I'll open another channel with Dmitry about how best to do this. 

Closing this issue.
