### ISSUE TITLE
AutoML API model incompatible with AutoML CLI?

### ISSUE THREAD

**Issue by famschopman** [dotnet/machinelearning-modelbuilder#694]
When I train and save a model with the ModelBuilder from Visual Studio, and inspect the model that is loaded to predict I get a TrainSchema with all columns, and the last column is the Features column.

When I train and save a model with the AutoML API, it received an exception where it tries to find a SamplingKeyColumn. After inspection AutoML has saved the model with an additional column just before the Features column. This is different compared to the ModelBuilder behavior.

So I have to extend me model with the following lines to make sure I can run a prediction (I have 34 columns in my dataset).

            [ColumnName("SamplingKeyColumn"), LoadColumn(35)]
            public float SamplingKeyColumn { get; set; }

Is this expected behavior? It feels very inconsistent and quite confusing behavior. I couldn't find any documentation about this either.

**Comment by LittleLittleCloud** [comment]
Seems like a bug in AutoML.Net 
@justinormont  is this one been fixed or not?

**Comment by justinormont** [comment]
> @justinormont is this one been fixed or not?

I don't think it's been fixed.

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud Can you look into this?

**Comment by antoniovs1029** [comment]
So I believe this is actually an issue on ML.NET's `mlContext.Data.TrainTestSplit()` and `mlContext.Data.CrossValidationSplit()` as explained here:
https://github.com/dotnet/machinelearning/issues/5256#issuecomment-649883054

But I'm unsure if the OP of this issue here ( @famschopman ) used these methods? Can you still provide a full repro of your issue?

My suspicion is that when the user says "When I train and save a model with the AutoML API", it means that they used code similar to the one on https://github.com/dotnet/machinelearning/issues/5256#issue-645470923 , where TrainTestSplit() or CrossValidationSplit() was actually used before calling AutoML? and not the CLI?

**Comment by beccamc** [comment]
@LittleLittleCloud Is this fixed?

**Comment by famschopman** [comment]
I am not sure if I still have the code laying around to help you with a repro, but if needed just ping me and I will try to find. I will be picking up ML.Net soon again. First have to finish some other software first ... 😘

**Comment by luisquintanilla** [comment]
@LittleLittleCloud since this references the old AutoML API, I think we're okay to close  unless it continues to be an issue.

**Comment by LittleLittleCloud** [comment]
Close since this issue is related to old AutoML API, feel free to reopen it if you have questions
