### ISSUE TITLE
[Functional Spec] Feature Selection -  User can select columns to use as features.

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#75]
- [ ] Custom UI Picker
  - [ ] Select All
  - [ ] Clear
  - [ ] Search/Filter
  - [ ] Check Box
  - [ ] Disabled (Label)
- [ ] Column Tracking/View Model
  - [ ]  Managing state of columns
    - [ ] Label
    - [ ] Feature
    - [ ] Ignored
- [ ] Passing Feature Selection to CLI
  - [ ] Create MLTrainParameters with a subset of columns as features (--ignore-columns)
    - [ ] MLTrainParameters - Args
    - [ ] CliInstance - Call Into CLI

**Comment by rustd** [comment]
@briacht can you please add the link to the spec here?

**Comment by briacht** [comment]
Spec: https://microsoft-my.sharepoint.com/:w:/p/brachtma/EWTwDcE60yxIvxJTBP3IyPAB5x0qFZ7fUPGbajdrvlhE5w?e=i3qh6u

**Comment by greazer** [comment]
Needs spec label needs to stay on until we have all the information necessary to cost the feature. Basically the design is part of the spec.

**Comment by rustd** [comment]
Had the UX design review yesterday

**Comment by greazer** [comment]
@rustd please add a link to the design.

**Comment by greazer** [comment]
@rustd  Re-adding Needs Spec until we have the design link in place and the design signed off.

**Comment by rustd** [comment]
UX design spec.
https://www.figma.com/file/Wv5z7YBvuzaCTpQt7i1qxEXZ/ML.NET-Model-Builder%3A-Feature-Engineering-Deliverables?node-id=1%3A47

**Comment by greazer** [comment]
@rustd  Please see the comments in Bri's spec from Justin Ormont. From what I'm understanding the number of columns that users are likely to run into is typically going to be higher than 100. The average for TLC GUI Wizard was 208. To me, this implies that we have a potential design problem that we should  test in front of real users before we implement.

**Comment by LittleLittleCloud** [comment]
@rustd Got 404 when opening UX design spec page, can you grant me permission?

**Comment by rustd** [comment]
You need to login using Microsoft credentials. Please ping @iampiyusharora for access if you can't access it.

![image](https://user-images.githubusercontent.com/1132652/60222814-97db5a80-9833-11e9-9bb6-2c68d67b5cb7.png)

**Comment by justinormont** [comment]
Any reason to not post the GUI design publicly?

**Comment by justinormont** [comment]
Some feedback:
* The column search is really nice; I was having some issues with this previously
* I'd recommend keeping columns in their original order; currently they are sorted alphabetically
* Clip column values to N characters (~40?); perhaps hover to see longer values, or force the user to resize the column
* Allow selecting/deselecting columns as features from the header (maybe on/off or use/ignore or on/ignored)
* We will need more [column purposes](https://github.com/dotnet/machinelearning/blob/features/automl/src/Microsoft.ML.AutoML/ColumnInference/ColumnPurpose.cs) besides `Label`, `Ignore` (and default/implicit the `Auto`)
  * `Auto` (when not otherwise overridden)
  * `Ignore`
  * `Label`
  * `NumericFeature`
  * `CategoricalFeature`
  * `TextFeature`
  * `Weight`
  * `ImagePath`
  * `SamplingKey`
  * `Time` (future column purpose forecasting)
  This implies we want to give the user these controls within Model Builder (and I think we do). To support these, we may want a drop down per column to select the purpose. These can be auto-set by calling the AutoML `InferColumns()` API.
* "Next" buttons are too small and don't look like buttons -- eg: "Next Step: Evaluate"
* If there is only one next thing to do, like click a "next" button, do it for the user
* Automate the running, start the AutoML process as soon as enough information is gathered, why wait?
* The start page lists sentiment analysis as binary classification; sentiment analysis is often 3 classes  of negative/**neutral**/positive instead of binary<sup>[[1]](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-quickstart-intent-and-sentiment-analysis)[[2]](https://en.wikipedia.org/wiki/Sentiment_analysis#Types)[[3]](https://monkeylearn.com/sentiment-analysis/)</sup>. Aside from being an imperfect example, I'd also like to move users away from the concept of binary classification and simply have "classification" where the user won't have to worry about how many classes their dataset has. ([more info](https://github.com/dotnet/machinelearning-automl/issues/390)).

**Comment by greazer** [comment]
We finalized the review of this functional spec. A couple items of note:
1) We have decided that for the first release we will assume that most users will have 50 or less columns. 
2) We will check current CLI telemetry as well as add a new telemetry point to MB to send back the number of columns in tables and number of columns being selected.
3) The dropdown column chooser is more readily visibly appealing, however, having the search significantly delays our ability to ship this functionality. Therefore, we are not going to support search for columns in the first release.
3a) The column/feature chooser will be a simple combo box with checkboxes. 
4) Showing or allowing the user to select columns by index is out of scope for the first release.

@briacht , @rustd, please take some time asap, to look through the CLI telemetry to see if we can make an initial determination that not worrying about datasets with columns > 100 is warranted.

**Comment by justinormont** [comment]
From this month's CLI telemetry:
* 5th percentile is 2 columns
* 25th percentile is 7 columns
* 50th percentile is 7 columns
* 75th percentile is 18 columns
* 90th percentile is 94 columns
* **95th percentile is 174 columns**
* **99th percentile is 785 columns**
* Max is 139,000 columns
* Average is 160 columns

This is raw usage; it would be slightly better count distinct datasets, and to remove runs on our example datasets. 

These stats includes both direct CLI usage, and indirectly, Model Builder.

**Comment by greazer** [comment]
Justin, it’s not clear to me what the percentile technically means here. Can you clarify? I think you’re basic point is that for people using the ML.NET CLI and Model Builder, most datasets being pulled in have a very high column count.

**Comment by greazer** [comment]
Ah, figured it out. 75% of people using the CLI or MB have 18 columns or less. At least that's the only thing that seems to make sense to me.

**Comment by justinormont** [comment]
@greazer: Correct. 

To cover 95% of our users, we want 174 columns to work well in the GUI. 
For 99% of the users to have a good experience 785 column have to work well.

The actual column counts are higher than this. This includes a very large number of runs on our three example datasets; these toy datasets do not have many columns and skews our column counts lower than reality.
