### ISSUE TITLE
Training time finished without any models trained.

### ISSUE THREAD

**Issue by khalid-cmd** [dotnet/machinelearning-modelbuilder#838]
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment]
Sorry you've run into problems and thanks for reporting @khalid-cmd! Did you try to increase the training time? If you're using a sample from online 60 seconds is usually enough. 

Otherwise, can you provide more info so I can investigate further?
- Visual studio version
- Model Builder version
- What scenario you tried?
- Can you share the dataset? 

Thanks!

**Comment by beccamc** [comment]
@khalid-cmd Friendly ping on the above questions

**Comment by beccamc** [comment]
Unfortunately we don't have enough information to investigate this issue. If you're still seeing a problem, please re-open and provide additional information. Thanks for reporting!
