### ISSUE TITLE
result.Prediction type

### ISSUE THREAD

**Issue by T5chrono** [dotnet/machinelearning-modelbuilder#857]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hi, In the final step I am getting the output for console app still like 1 and 0 instead of true/false. 
From line: Console.WriteLine($"Text: {input.SentimentText}\nIs Toxic: {result.Prediction}");
Not a big deal really.

**Comment by LittleLittleCloud** [comment]
It's because value for your label is 1/0. 

To be detailed, we used to try parsing label type as boolean before but we found it might be confuseing in some cases, (for example, should we also parse value "true", "false" to boolean? if so the output will be "True", "False", which just does too much and might not be expected. So then we decided to keep label's value as what it is.

**Comment by LittleLittleCloud** [comment]
Close due to no response, feel free to reopen it if you still have the problem
