### ISSUE TITLE
Multiple Models in one solution

### ISSUE THREAD

**Issue by adrianbegi** [dotnet/machinelearning-modelbuilder#878]
Currently there is no way to name the Model Builder projects. So if you wanted to add multiple models to one solution through the model builder you will have to overwrite the previously built model projects. Is there a way around this?

**Comment by LittleLittleCloud** [comment]
Hi @adrianbegi 
The model name depends on solution name, so in order to avoid the new model overwriting the old one, you can rename the model and generated model project to a new name.

We are aware of such restriction is inconvenient and we are working on removing this overwriting behavior so multiple model with custom-defined name can be added, it will come out soon. But right now you can rename model as temporary solution

**Comment by adrianbegi** [comment]
@LittleLittleCloud thanks for the update.

**Comment by LittleLittleCloud** [comment]
I'm going to close this issue since we have #846  to track down this topic, feel free to reply in that thread.

**Comment by JakeRadMSFT** [comment]
Related to #616
