### ISSUE TITLE
Feedback link UI inconsistencies, icon inconsistency

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#925]
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.1.2038102
 - Visual Studio Version

**Describe the bug**
1. The feedback icon (Blue Theme) appears to be filled with blue color. It should be exactly how the main feedback icon on top-right of VS is.

2. The 'Suggest a feature' icon inside the dropdown appears to be filled (blue theme). It should be exactly how the main feedback dropdown is on the top-right of VS.

3. The dropdown for Give Feedback isn't themed. It should use the same theming as the feedback dropdown (top-right of VS).

**To Reproduce**
1. Go to Machine Learning Model Builder

**Expected behavior**
Described above.

**Screenshots**
![image](https://user-images.githubusercontent.com/48927690/89079873-49ed2c00-d33c-11ea-9856-65257e63fa6b.png)

**Additional context**

**Comment by beccamc** [comment]
I've taken a look at items 1&2. We pull our icons from this list http://glyphlist.azurewebsites.net/knownmonikers/

1. I'm not sure why the feedback icon is blue. In other themes it matches the same as the upper right icon. VS is automatically updating it to a dark background. This is light theme, and it matches the upper right. 
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/1be2c20b-87d6-4bf8-a39d-0cb6597a1f94)
2. I don't see an "MessageBubbleOutline" icon or similar. 

It seems like the icons we have access to, and the ones being used in the upper right are different. Is there another place we should be getting icons from?

**Comment by beccamc** [comment]
On item 3.  Here are the two menus open side by side 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/1924ee96-9cc5-47a7-b538-8a99ca1c17dc)

They seem to be the same size. A few differences...
 - Icons are slightly smaller on our side. We can increase the size. 
-  Background color is different. This appears to me to be because ours launches from the white background area of the code page, and the menu launches from the gray/tan of the menu area. They are matching their parent background colors. 

We can increase the icon size, but is there something else we should do to improve this?

**Comment by romalpani** [comment]
Hi Becca,
1. Can we ensure that the icons are the same size as the ones on the global feedback button in VS, as well as the distance between icon and text?
2. The blue color of the icon is a weird issue. I will check with the icons team to see if there's any other moniker to use.
3. Is the problem with the "Suggest a feature" icon the same as above? 
4. To keep it consistent with the global feedback flyout, could we make these changes?
Title case and ellipses at the end.
"Report a Bug (GitHub)..."
"Suggest a Feature (GitHub)..."

**Comment by beccamc** [comment]
Hi Rohan!
1. Yes we can ensure icons size and spacing is the same. 
2. Would be great if you can check on the blue icon moniker
3. Suggest a feature icon is similar. We are using the MessageBubble moniker and that is how it looks. This is the only one I see that looks correct:
![image](https://user-images.githubusercontent.com/9122518/129075928-bc82e20d-1189-43cf-b0db-5c209ad85d5f.png)
4. Yes we can make those rename changes. 

Devs: 
- [ ] Ensure that the icons are the same size as the ones on the global feedback button in VS, as well as the distance between icon and text
- [ ] Change strings. Title case and ellipses at the end.
"Report a Bug (GitHub)..."
"Suggest a Feature (GitHub)..."

Design: 
- [ ] Check on which monikers we should be using for the problem icons.

**Comment by chryw** [comment]
@romalpani I think the monikers are correct.
- Blue feedback icon: This is because `ImageThemingUtilities.ImageBackgroundColor` is not set and not reflecting the actual background.
  ![image](https://user-images.githubusercontent.com/7075677/129807281-a0748a21-e4bc-4d3b-906f-67b82e567d81.png)
- Bubble icon: 
  - The global command bar is using `Comment` moniker 
  ![image](https://user-images.githubusercontent.com/7075677/129808937-400781bd-1557-4b14-aa05-d50022aeca2f.png) 
  - The `MessageBubble` moniker looks like this in the **old** icon style
   ![image](https://user-images.githubusercontent.com/7075677/129808910-e21d501e-b284-41c8-b1b9-9842d1fede00.png)
  But we've consolidated the two monikers to have the same design in the new icon style. 
  ![image](https://user-images.githubusercontent.com/7075677/129809216-b96fca01-7e33-421c-95e4-bc8662eacd9f.png)
  ![image](https://user-images.githubusercontent.com/7075677/129809162-79d28878-0c41-41de-b4f1-3772f90659c6.png)
  - **You can keep your current moniker reference as `MessageBubble`.** It'll look good once we fully deprecate the old image catalog.
- I also noticed the other card images also have issues when switching themes:
![image](https://user-images.githubusercontent.com/7075677/129807360-5e6af331-543c-4b8a-b769-c434edafa3ce.png)
![image](https://user-images.githubusercontent.com/7075677/129807407-5a2f599a-b6e4-4f57-be1a-82e86a8683ac.png)

**Comment by romalpani** [comment]
@beccamc ^^ does that help? 
Seems like, for the message bubble icon, we just need to wait.

**Comment by beccamc** [comment]
Yes, thanks for the assistance here Cherry!

**Comment by luisquintanilla** [comment]
@romalpani I have this as needing docs. Is there anything needed from our end?

**Comment by romalpani** [comment]
I am not sure what documentation this particular issue would need. May be the “Needs docs” label was attached by mistake, but I don’t see one right now on the issue.

From: Luis Quintanilla ***@***.***>
Date: Wednesday, September 1, 2021 at 2:07 PM
To: dotnet/machinelearning-modelbuilder ***@***.***>
Cc: Rohan Malpani ***@***.***>, Mention ***@***.***>
Subject: Re: [dotnet/machinelearning-modelbuilder] Feedback link UI inconsistencies, icon inconsistency (#925)

@romalpani<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fromalpani&data=04%7C01%7CRohan.Malpani%40microsoft.com%7C00bc4b33f93847807fc708d96d8c85e9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637661272584335908%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XPcmWuu3wt1upzCArkvdzo8zZbHHaMN5PCopX8p2Xro%3D&reserved=0> I have this as needing docs. Is there anything needed from our end?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fmachinelearning-modelbuilder%2Fissues%2F925%23issuecomment-910755639&data=04%7C01%7CRohan.Malpani%40microsoft.com%7C00bc4b33f93847807fc708d96d8c85e9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637661272584345901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BqoO%2B9W1AJzDePEqtP%2FHNGpBAOl8%2F6j4L80kRRNFA1E%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALVJHSRY75WSNITHPPBYCNDT72IZPANCNFSM4PQ6KPYQ&data=04%7C01%7CRohan.Malpani%40microsoft.com%7C00bc4b33f93847807fc708d96d8c85e9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637661272584345901%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=v6WmdIg2l1E2ZAdXUThA1N1nsGEC3GHzf2XmCAV3NDU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CRohan.Malpani%40microsoft.com%7C00bc4b33f93847807fc708d96d8c85e9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637661272584355894%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ibmaeWs3s2XgnY3Y%2FwBJAmm1GP%2BanFzfNnWxv3UFqmo%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CRohan.Malpani%40microsoft.com%7C00bc4b33f93847807fc708d96d8c85e9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637661272584355894%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4ntyIBJpjinELvX17kAO3WpN25Q22wFgF961ThJEWaE%3D&reserved=0>.

**Comment by beccamc** [comment]
- [x] Icons are larger
- [x] Message icon is outline instead of filled
- [x] Title case and ellipses at the end of text
- [x] Smaller spacing between text and icon

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/cbc4b69b-a640-458c-acba-00d1ec67c9af)

**Comment by chryw** [comment]
Thanks @beccamc ! I forwarded this to UX team.
> * [x]  Icons are larger
> * [x]  Message icon is outline instead of filled
> * [x]  Title case and ellipses at the end of text
> * [x]  Smaller spacing between text and icon
> 
> ![image.png](https://camo.githubusercontent.com/de2f9ea125512f92b929876a697c63b08e3acdd7a5c609ca7e32076028142ce9/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564353563336436386661633834303030313331346561612f63626334623639622d613634302d343538632d616362612d303064316563363763396166)
