### ISSUE TITLE
ModelBuilder Tries to overwrite old models (relates to #878)

### ISSUE THREAD

**Issue by forReason** [dotnet/machinelearning-modelbuilder#995]
**System Information (please complete the following information):**
 - Model Builder Version: Current
 - Visual Studio Version: Current

**Describe the bug**
When training a new model and trying to save it to the solution, Modelbuilder will warn for overwrite, eventhough I have renamed the Model

**To Reproduce**
1. Train a Model
2. Within the Solution. rightclick -> rename the Model
3. Train new Model
4. Try to add new model to Solution

**Expected behavior**
A model name can be specified

**Additional context**
I have renamed my model so that my Solution now looks like the following:
![image](https://user-images.githubusercontent.com/12736950/93100503-82a55280-f6a9-11ea-8a14-8ae69c9f4e85.png)

Still for some reason it will tell me that the model will be overwritten. Additionally it still seems to refer to the old model name so i'm afraid not all references got updated. How do I proceed or what further steps do I have to do in order to lad additional models?

**Comment by JakeRadMSFT** [comment]
@forReason hello again! Thanks for reporting - supporting multiple models (end of year) and versioning of models (shortly after multiple models) is in our future plans. We're planning on having it work more like WPF/WinFroms where "models" will be an item instead of a separate project. This will allow you to have multiple Model Builders open and allow you to re-open the items with all of the same Model Builder state.

Thanks for reporting! It really helps define our future direction!

**Comment by forReason** [comment]
sounds good but what do I still need to do right now so that my model is safe? I that step I did with renaming correct?

Or can I somehow import previously trained Model builder models?
